### PR TITLE
Improved support of the emailRequired property

### LINKED ISSUE #5553: Cannot have two or more users without email when emailRequired is disabled
### What steps will reproduce the problem?
1. Disable emailRequired in common.php for the user module.
2. Create more than one user without email in the admin menu.
3. (Optional) Edit a user and remove the email --> will not save

### What is the expected result?
Also have more than 2 users without email

### Additional info
I will upload the fix in a moment :)

| Q                | A
| ---------------- | ---
| HumHub version   | since 1.2.2?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

### PR DESCRIPTION
**Pull request by KarlKeu00**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [X] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [X] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
- Fix #5553 
- Since in the database the email row is unique (and better should remain so), a random invalid email is generated for each user who has not stored an email.
- The email is guaranteed to be invalid because the TLD has been reserved (https://en.wikipedia.org/wiki/.invalid).
- Sorry for #5554, I'm still practicing a bit to deal with GitHub :)

### CODE REVIEW

**Comment by KarlKeu00** [comment]
Oh, right. I must have overlooked that.
But still there is the error that for an existing user the email can not be removed. I think the problem is that the HForm supports "required" but not in combination with "when". So the changes in User.php would still have to be partially applied.

**Comment by luke-** [comment]
@KarlKeu00  Yes ok, the fix regarding HForm is good!

Maybe it also makes sense to add a "beforeSave" and make sure that empty email values are always null?

e.g.
```php
if ($this->email == '') {
    $this->email = new \yii\db\Expression('NULL');
}
```

**Comment by KarlKeu00** [comment]
My understanding until now was that MySQL normally replaces an empty string with NULL. This makes total sense from a technical point of view: An empty string consists only of one \0 "character" = NULL. But I don't know how this looks like with other or older databases. But this additional protection certainly helps to avoid errors.

**Comment by KarlKeu00** [comment]
Just implemented the changes.
In the BaseFormAuth.php I have kept parts of the change anyway (more readable)
In User.php the line 12 was not used and could be removed.

**Comment by KarlKeu00** [comment]
Just implemented the changes.
Sorry for the many commits - still have to practice with GitHub and the collaboration feature...

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@KarlKeu00 Thank you and no problem. I did a squash commit. 
https://github.com/humhub/humhub/commit/cb000a1f72e95aeb80969b1444c9544c95cc5861

**Pull request closed without merging**
