### PR TITLE
allow customization of Stream action via events

### PR DESCRIPTION
**Pull request by cebe**
added before and after action events that can be used to modify the
stream action filter.

### CODE REVIEW

**Comment by 001101** [comment]
Can you please explain how i now can customize a stream after this update?

**Comment by cebe** [comment]
For customization form a module, you can register an event handler in module config:

```php
    // to customize all streams
    ['class' => \humhub\modules\content\components\actions\Stream::className(), 'event' => \humhub\modules\content\components\actions\Stream::EVENT_BEFORE_RUN, 'callback' => ['humhub\modules\mymodule\Events', 'onStreamActionBeforeRun']],
    // OR to customize a specific stream (in this case the dashboard)
    ['class' => \humhub\modules\dashboard\components\actions\DashboardStream::className(), 'event' => \humhub\modules\dashboard\components\actions\DashboardStream::EVENT_BEFORE_RUN, 'callback' => ['humhub\modules\mymodule\Events', 'onStreamActionBeforeRun']],
```

The event handler would look like this:

```php
    /**
     * @param ActionEvent $event
     */
    public static function onStreamActionBeforeRun($event)
    {
        /** @var $action Stream */
        $action = $event->action;

        $action->activeQuery->andWhere(/* your custom condition */);
    }

```

**Comment by 001101** [comment]
Ah I understand now, thanks! Could you tell me how I can change the notifications when a user register and joins the default spaces, because that blows the activity streams (i have 28 default join spaces).

**Comment by cebe** [comment]
you could check for `$this->mode == self::MODE_ACTIVITY` and the filter out the activity you are interested in. Not exactly sure how to do that.

**Pull request merged**
