### PR TITLE
fixup! Enh: Add Application interface and make sure the `onInit` even…

### PR DESCRIPTION
**Pull request by martin-rueegg**
See
- https://github.com/humhub/humhub/pull/6519#issuecomment-1682536154
- https://github.com/humhub/humhub/pull/6505

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by martin-rueegg** [comment]
@luke- I've double tested it locally and can't reproduce the error. Both the test suite as well as when I do it manually in the browser it works. Using PHP v8.2 ....

I guess it could be a timing issue, that the post has not yet been replaced with the non-draft post. I've added a wait of 2 seconds into the test ...

**Review by luke- — APPROVED** [review]

**Comment by martin-rueegg** [comment]
Thanks. Would you mind updating `statable` branch at some point, too?

**Comment by luke-** [comment]
Justed merged `develop` into `statable` or is it better to merge `next` into it?

**Comment by martin-rueegg** [comment]
> Justed merged `develop` into `statable` 

Thank you. 

> or is it better to merge `next` into it?

Thanks, appreciated! - Not until it is clear if (any version of) `FindInstance` will make it into develop ...

**Comment by martin-rueegg** [comment]
@luke- Another thing that came to my mind is if you like the idea of the new namespace `humhub\interfaces`, as currently most interfaces are alongside some of the classes.

Now for a`ApplicationInterface` that would then probably be `humhub\components\ApplicationInterface`.

I personally prefer having the interfaces in their own namespace, as the do not always concord with the implementing classes, as we can see with `humhub\components\console\Application`. However, I just wanted to (consciously) run it by you.

**Comment by luke-** [comment]
@martin-rueegg I like to have now `humhub\interfaces` in addition to newly introduced `humhub\helpers`. It will take some time to move core interfaces into it. I hope we can sometimes use rector for such things.

**Comment by luke-** [comment]
@martin-rueegg I don't know if realistic, but cool would be e.g. a
`php protected/yii rector/migrate-module /path/to/module`
which automatically applies some changes from the `MIGRATE-DEV.md`.

**Comment by martin-rueegg** [comment]
Haven't used or even looked into rector yet. But certainly something to keep in mind and that would be a perfect approach. `migrations` for the code!

**Pull request merged**
