### PR TITLE
Forbid to open AJAX actions as separate page

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/3733

### CODE REVIEW

**Review by luke- — APPROVED** [review]
Merge in 1.9

**Comment by buddh4** [comment]
Just a suggestion, should we name the access rule just `ajax`, we have another rule `json`. When implementing (and not using the const) its easier to remember `ajax` instead of `onAjaxOnly`. I know its a more descriptive, but I think both names are clear enough.

**Comment by luke-** [comment]
Do you mean only the value or also the name constant?

For me it's ok when we change the value of the constant to "ajax" only, otherwise I would prefer the name RULE_AJAX_ONLY  because it is very descriptive.

**Comment by buddh4** [comment]
Yeah, we can keep the constant name but change the value. Ideally the constant is used anyways.

**Comment by luke-** [comment]
Added to Migratin Docu: https://github.com/humhub/documentation/blob/develop/docs/develop/modules-migrate.md#migrate-from-18-to-19

**Pull request merged**
