### PR TITLE
Convert assert* and db* methods to `static`, in line with general usage pattern

### PR DESCRIPTION
**Pull request by martin-rueegg**
**What kind of change does this PR introduce?**

- Refactor

**Does this PR introduce a breaking change?** (check one)

- No

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] [All tests are passing](#issuecomment-new)
- [x] Changelog was modified

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@martin-rueegg Thanks for the PR. 

A question, since the methods are used in some modules: Do you know if it is safe when we call these new static methods, continue using the instance? Or is there a warning/deprecation here?

Actually, it would be best to refactor the modules as well...

**Comment by martin-rueegg** [comment]
AFAIK, @luke-, the call to a static method works also in the instance notation (i.e. `$this->method()`, rather than `static::method()` or `$object::method()`). I was only notified in PhpStorm to use static call notation in tests, but they succeeded anyway.

But yes, updating the modules (and the tests themselves) might be a good (although not urgent) approach.

**Comment by martin-rueegg** [comment]
@luke- 

> Actually, it would be best to refactor the modules as well...

Shall we create an issue for the above?

... and merge this PR?

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@martin-rueegg Thanks, I've just merged this PR. I'll create an internal tasks for refactoring the modules, but since a static method can also called by instance, there is no problem here.

**Comment by martin-rueegg** [comment]
Awesome. Thank you!

**Pull request merged**
