### PR TITLE
Added check for APCu to installation checks

### LINKED ISSUE #2005: PHP 7 + ZendOpcache + APCu
Hi,

I use PHP 7, ZendOpcache and APCu extension with Apache2. Humhub reports APC support as not installed although APCu should have the required functionality as a cache.

### PR DESCRIPTION
**Pull request by cebe**
fixes #2005

### CODE REVIEW

**Comment by luke-** [comment]
We also should add this to:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/models/forms/CacheSettingsForm.php#L72

Is there anything else necessary to support APCu on Yii2 side?

Thanks!

**Comment by cebe** [comment]
You need to enable a switch in ApcCache class: https://github.com/yiisoft/yii2/blob/63f95fa3adc73fc479514cfdc856cd25f75d4cec/framework/caching/ApcCache.php#L33 that's all.

**Comment by Lokyaziis** [comment]
Works fine for me... Thanks !!

**Comment by ShalokShalom** [comment]
Where is this?

http://funkyimg.com/i/2nbtL.png

**Pull request merged**
