### PR TITLE
Ukrainian translation for topic module.

### PR DESCRIPTION
**Pull request by glodov**
Permissions file.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Localization.
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@glodov Thanks for your contribution, please use our translation site for further translations:
https://translate.humhub.org/

**Comment by glodov** [comment]
> @glodov Thanks for your contribution, please use our translation site for further translations: https://translate.humhub.org/

Thank you!
Waiting for approval of my registration there.

**Comment by luke-** [comment]
@glodov You should be approved. Can you please approve your CLA using following link https://cla-assistant.io/check/humhub/humhub?pullRequest=6072

**Comment by glodov** [comment]
> @glodov You should be approved. Can you please approve your CLA using following link https://cla-assistant.io/check/humhub/humhub?pullRequest=6072

did it work?
I cannot see any change after following this link. I am a redirected to the current page.

**Comment by luke-** [comment]
https://cla-assistant.io/humhub/humhub?pullRequest=6072

**Comment by glodov** [comment]
Signed.

**Review by luke- — APPROVED** [review]

**Pull request merged**
