### PR TITLE
Fix: Misplacement of both Likes & Comments

### PR DESCRIPTION
**Pull request by Felli**

### CODE REVIEW

**Comment by buddh4** [comment]
What exactly is misplaced, do you have a screenshot?

**Comment by Felli** [comment]
Within custom themes the comment button will always come before the like but, even with the Wiki module, with this it will force the like button to come first.

**Comment by acs-ferreira** [comment]
I've tried this _(trough Firebug)_ here is what i get:

image

Also, `Comment` is always the first link, even in HumHub default theme, am i wrong?

**Comment by Felli** [comment]
As @acs-ferreira said; Comments are seen as first within an installation of the software, using this does provide a fix, I've tested myself on my personal servers with success. The only issue that I face now is fixing the like a comment...
untitled

**Comment by acs-ferreira** [comment]
Ok, i see @Felli , but i prefer to have **Comments first** ;)
_Personal opinion, nothing else. Is this is merged, i'll revert it locally._

**Comment by buddh4** [comment]
So, I close this for now, I don't see this problem in the community theme?

**Comment by Felli** [comment]
I suspect this is an issue that happens for self hosted sites.

**Pull request closed without merging**
