### PR TITLE
Check Codeceptions Tests

### PR DESCRIPTION
**Pull request by gevorgmansuryan**
https://github.com/humhub/humhub-internal/issues/473

### CODE REVIEW

**Comment by gevorgmansuryan** [comment]
There was issue related application installed state in test environment. Still in progress

**Comment by gevorgmansuryan** [comment]
The problem is that application installed state now works based on database, but before starting tests the database is being cleared. Still in progress

**Comment by luke-** [comment]
@gevorgmansuryan Thanks for the update.

**Comment by gevorgmansuryan** [comment]
Will be fixed by https://github.com/humhub/humhub/pull/7361, as it's related with applicationState

**Pull request closed without merging**
