### PR TITLE
Fix scheduled post visibility on permalink

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/6515

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Does this affect also other content types?

**Comment by ArchBlood** [comment]
> @yurabakhtin Does this affect also other content types?

I believe it affected all content that can be scheduled.

**Comment by yurabakhtin** [comment]
> @yurabakhtin Does this affect also other content types?

@luke- No, I have done this only for the Post view action.

If we need to apply this for all contents then I think we should modify the default `StreamQuery->stateFilterCondition` (https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/models/StreamQuery.php#L152) from:

- `['OR', ['content.state' => Content::STATE_PUBLISHED]]`

to:

- `['OR', ['content.state' => Content::STATE_PUBLISHED], ['content.created_by' => Yii::$app->user->id]]`

But I am not sure it is correct solution, because probably we should not display for example all deleted contents in stream when the filter "Deleted" is not selected.

Ok, I will review again how to apply the rule `['content.created_by' => Yii::$app->user->id]` for all content types but only for action "View content".

**Comment by yurabakhtin** [comment]
@luke- Ok, I have decided to allow for creators to see content with any state.
Commit https://github.com/humhub/humhub/pull/6540/commits/7ce1f98e0907a52666dda0fa7e688df4ae5dcacd.

Really it would be better for all such view actions remove the filter `->readable()` and replace it with code:

```
if (!$record->content->canView()) {
    throw new ForbiddenHttpException();
}
```

so after this all not published contents will be available for all users(admin, managers) who can view the record and not only a creator.
But the modification requires to find all such actions in all modules(wiki, news, etc.).
I think better to keep the `->readable()` because it seems the `->canView()` is already integrated in the `->readable()` with `$this->andWhere("{$conditionSpace} OR {$conditionUser} OR {$globalCondition}");` and I am thinking we just should append here the `$this->stateFilterCondition`, so a Content will be visible when `'content.state' => Content::STATE_PUBLISHED` or if user has at least one permission related to the `{$conditionSpace} OR {$conditionUser} OR {$globalCondition}`, I will test this case, so the PR is not ready for merging yet.

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/6540/commits/16f9314cbaca836b717be6e7f9b30ceb2a6552de - I think this solution is better when we allow to view Content with any State if current User has a permission to view it.

The code:

```php
$this->stateFilterCondition[] = $conditionUser;
$this->andWhere($this->stateFilterCondition);
```

is equivalent of:

```
content.state = 1
OR content.created_by = 1
OR (cuser.id IS NOT NULL
    AND (content.visibility = 1
        OR (content.visibility = 0 AND content.contentcontainer_id = 1)
        OR (content.visibility = 0 AND cff.id IS NOT NULL)
    )
)
```

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Here it would be good to provide some unit tests for it.

Do I understand correctly that before your change `readable()` returned only `STATE_PUBLISHED` content and now it returns all states?

**Comment by yurabakhtin** [comment]
> Do I understand correctly that before your change `readable()` returned only `STATE_PUBLISHED` content and now it returns all states?

@luke- Yes, all states if current user can view a Content.

> Here it would be good to provide some unit tests for it.

Ok, I will create it.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/6005

**Pull request closed without merging**
