### PR TITLE
Don't check email for existing on password recovery

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
https://github.com/humhub/humhub-internal/issues/441#issuecomment-2462073750

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
- We also need to run this check, after the mail validation: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/forms/AccountRecoverPassword.php#L70-L75 

- Can you please rebase to `develop`.

**Comment by yurabakhtin** [comment]
> * We also need to run this check, after the mail validation: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/forms/AccountRecoverPassword.php#L70-L75

@luke- Do you mean we should remove the code completely?
We will not display the error:

err-mes

We will display the message:

after-recover

and don't send any email to such users, right?

**Comment by luke-** [comment]
@yurabakhtin We should also send an e-mail to the users. Only after they click the link in the e-mail should the error message appear.

**Comment by yurabakhtin** [comment]
> @yurabakhtin We should also send an e-mail to the users. Only after they click the link in the e-mail should the error message appear.

@luke- Commit https://github.com/humhub/humhub/pull/7298/commits/13828d42cf8b02be81bb1c7285a49a8e298bd22b:

no-password-recovery

Please note I used the error message `'Password recovery disabled. Please contact your system administrator.` that was used before.

For users with password it works this way:

has-password-recovery

**Review by luke- — APPROVED** [review]

**Pull request merged**
