### PR TITLE
Fix: In lists, when an item text is displayed on multiple lines, the …

### PR DESCRIPTION
**Pull request by marc-farre**
…lines below are not lining up with the first one

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by marc-farre** [comment]
@luke- 

Before:
image

After:
image

**Comment by luke-** [comment]
@marc-farre Thanks! Maybe this is something we should merge against master?

Maybe related: https://github.com/humhub/humhub-internal/issues/330

@yurabakhtin @Eladnarlea Do you have any concerns here?

**Comment by marc-farre** [comment]
@luke- yes, I was a little unsure of which branch. I'll do it for the Master one, but I will first wait for @yurabakhtin comment to see if it should be a dedicated PR or integrated into the other work you mentioned.

**Comment by Eladnarlea** [comment]
@luke- yes, please! No concerns :)

**Comment by yurabakhtin** [comment]
> Maybe related: [humhub/humhub-internal#330](https://github.com/humhub/humhub-internal/issues/330)

@luke- Yes, it is related.

@marc-farre I have tested this PR with [original issue](https://github.com/humhub/team_tasks/issues/342):

You can find this PR makes additional padding left, maybe it is ok because it seems other issues don't appear here, if it is ok then this PR can be merged.

**This PR:**
pr

**The `master` branch:**
master

---

**This PR:**

pr2

**The `master` branch:**
master2

**Comment by luke-** [comment]
@marc-farre For me it's fine. Do you see issues here?

**Review by luke- — APPROVED** [review]

**Pull request merged**
