### PR TITLE
Add button to show password

### PR DESCRIPTION
**Pull request by Themroc**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ArchBlood** [comment]
CSS should be added into the _**theme.css**_ for such a function and as much as I like to see more JavaScript, this should also be moved into its own file under _**/resources**_ but this is my opinion, I look forward to testing this out in full. :smiley:

**Comment by Themroc** [comment]
Well, if it were like 2 screens full of code, then yes. But why bother for such a tiny thingy? Re the css i  agree, i'm not happy with that <style>-block either.

**Comment by luke-** [comment]
The change should definitely be merged into the Develop Branch. Humhub 1.4 will also be released as beta soon.

@buddh4 Do you have a tip on how best to integrate Javascript?

**Comment by buddh4** [comment]
I've added this feature in the following commit:
https://github.com/humhub/humhub/commit/20be28039b4a33e08020fbac028e39e0155cd4fd

This also works for other password fields e.g. in change password etc.

**Pull request closed without merging**
