### PR TITLE
Add json extension as requirement

### PR DESCRIPTION
**Pull request by martin-rueegg**
`ext-json` was not in the list of required extensions. However, it's being used in the code.

### CODE REVIEW

**Comment by luke-** [comment]
Thanks. I've also added it here: https://github.com/humhub/documentation/blob/master/docs/admin/requirements.md

**Comment by martin-rueegg** [comment]
Awesome! Do we need to check it during installation, or is it done there?

**Comment by luke-** [comment]
> Awesome! Do we need to check it during installation, or is it done there?

I don't think it's necessary. Seem it's a core extensions with PHP 8.0+

**Comment by martin-rueegg** [comment]
> > Awesome! Do we need to check it during installation, or is it done there?
> 
> I don't think it's necessary. Seem it's a core extensions with PHP 8.0+

Sorry, just noticed your message now. It's now in the self test too, anyway. 🤷‍♂

**Comment by martin-rueegg** [comment]
I guess messing with `composer.json` requires to run a `composer update` to update `composer.lock`, which I don't feel like doing from my end.

Here the error log:
```

0s
Run composer validate
  composer validate
  shell: /usr/bin/bash -e {0}
  env:
    extensions: curl, intl, pdo, pdo_mysql, zip, exif, fileinfo, mbstring, gd, ldap
    key: cache-v2
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
    COMPOSER_CACHE_DIR: /home/runner/.cache/composer
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
# General warnings
- The package "yiisoft/yii2" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
- require.kartik-v/yii2-widgets : unbound version constraints (*) should be avoided
- require.npm-asset/animate.css : unbound version constraints (*) should be avoided
- require.npm-asset/blueimp-gallery : exact version constraints (2.36.0) should be avoided if the package follows semantic versioning
- require.npm-asset/humhub-prosemirror-richtext : exact version constraints (1.1.7) should be avoided if the package follows semantic versioning
- require.npm-asset/imagesloaded : unbound version constraints (*) should be avoided
- require.npm-asset/swiped-events : exact version constraints (1.0.9) should be avoided if the package follows semantic versioning
- require.raoul2000/yii2-jcrop-widget : unbound version constraints (*) should be avoided
- require.xj/yii2-jplayer-widget : unbound version constraints (*) should be avoided
Error: Process completed with exit code 2.
```

If you do that, would it make sense to also add

``` json
{
  "require": {
     "ext-pdo": "*",
  }
}
```

as well?

And potentially also 
``` json
{
   "require-dev": {
        "roave/security-advisories": "dev-latest"
  }
}
```

Also, is it worth adapt the version constraints as mentioned in the `# General warnings` above?

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
