### PR TITLE
Tour broken when profile start page is changed #4385

### PR DESCRIPTION
**Pull request by sahartak2025**
Tour broken when profile start page is changed #4385

### CODE REVIEW

**Comment by luke-** [comment]
Is there a reason why you do not use a direct link at this place? That might be a bit clearer.
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/tour/widgets/views/tourPanel.php#L45

Otherwise you can please choose the "Master" branch, because this is a bugfix.

**Review by luke- — CHANGES_REQUESTED** [review]
See comment

**Comment by sahartak2025** [comment]
> Is there a reason why you do not use a direct link at this place? That might be a bit clearer.
> https://github.com/humhub/humhub/blob/master/protected/humhub/modules/tour/widgets/views/tourPanel.php#L45
> 
> Otherwise you can please choose the "Master" branch, because this is a bugfix.

Not sure I understand, could you explain what does mean direct link ?

**Comment by luke-** [comment]
At the line sent before, you could use the direct URL here:


Not this action:
``` 
->createUrl('//user/profile', ['tour' => 'true']);
```

Instead:
``` 
->createUrl('//user/profile/home', ['tour' => 'true']);
```

This approach would avoid _tour_ module code (redirect fix) in the _user_ module.

**Comment by luke-** [comment]
Can we merge it?

**Comment by luke-** [comment]
@sahartak2025  It's still marked as Draft

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
