### PR TITLE
Topic add admin user privacy settings

### PR DESCRIPTION
**Pull request by acinelli**
Implemented Issue #548

### CODE REVIEW

**Comment by acinelli** [comment]
Let me know if you have any questions about this.  These preliminary privacy settings will be the base for adding a "friend" feature later as a separate pull request.  Later, the idea is we can add to privacy settings "Visible only to Friends".

**Comment by luke-** [comment]
Please apologize my late reply!
Can you create this PR for the develop branch again?
So we can better test & check new features.

Thanks!

**Comment by acinelli** [comment]
Sorry for the lag also, caught up with a different project.  I'll do 
this ASAP, thanks.


On 02/07/2015 05:38 AM, luke- wrote:
> Please apologize my late reply!
> Can you create this PR for the develop branch again?
> So we can better test & check new features.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/pull/549#issuecomment-73358978>.
>

-- 
Anthony Cinelli

**Comment by acinelli** [comment]
So make up to date with develop branch, or master branch? I've always 
synced with master branch for a PR is why I'm asking.


On 02/07/2015 05:38 AM, luke- wrote:
> Please apologize my late reply!
> Can you create this PR for the develop branch again?
> So we can better test & check new features.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/pull/549#issuecomment-73358978>.
>

-- 
Anthony Cinelli

**Comment by acinelli** [comment]
Trying to merge with develop branch, we've got a few conflicts.  One is 
in modules_core/users/views/profile/_layout.php where you've added 
"hideSidebar" to hide the sidebar completely, where I've added the 
ability to hide each component individually as explained back in Dec 27 
2014:
https://github.com/humhub/humhub/issues/548
"Admin can set default Privacy settings to show, hide this info on a 
user's profile, also allowing a user to override this default setting."

Let me know what you want to do with my changes.



On 02/07/2015 05:38 AM, luke- wrote:
> Please apologize my late reply!
> Can you create this PR for the develop branch again?
> So we can better test & check new features.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/pull/549#issuecomment-73358978>.
>

-- 
Anthony Cinelli

**Comment by acinelli** [comment]
FYI, I have no such conflicts merging with the hubhub master branch. 
I'll issue a new pull request from that so you can test cleanly with it.


On 02/07/2015 05:38 AM, luke- wrote:
> Please apologize my late reply!
> Can you create this PR for the develop branch again?
> So we can better test & check new features.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/pull/549#issuecomment-73358978>.
>

-- 
Anthony Cinelli

**Pull request closed without merging**
