### PR TITLE
#173 uisetting to set captcha removed

### PR DESCRIPTION
**Pull request by ultimocoder**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@ultimocoder Thanks, looks good. Can you please also update the changelog.

See info here: https://docs.humhub.org/docs/develop/pull-requests

**Comment by luke-** [comment]
@ultimocoder Can you please also check the failing tests?

**Comment by marc-farre** [comment]
I also suggest describing this change in https://github.com/humhub/humhub/blob/master/MIGRATE-DEV.md to then have it on https://docs.humhub.org/docs/admin/updating-migration2

**Comment by ultimocoder** [comment]
PR Closed as new PR raised for this issue.

check below path 
https://github.com/humhub/humhub/pull/7086

**Pull request closed without merging**
