### PR TITLE
Link color in markdown pages have same color as text Fix#121

### PR DESCRIPTION
**Pull request by MasterHans**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
We are discussing this issue in PR:
https://github.com/humhub/humhub/pull/4426

**The actual issue is :** 
The links resided in custom pages has the same color as a default website settings:

```
body a, body a:hover, body a:focus, body a:active, body a.active {
    color: #555;
    text-decoration: none;
}
```

1) Created custom.less file for customizing styles of custom pages.
2) Made all links inside the custom page - color: @llink.
3) Made hover of the links the same @link color and underlined text decoration.

**Note:** The hover property for links inside the stream, polls (comments , likes), wiki, media-heading, media-body is **switched off**

### CODE REVIEW

**Comment by luke-** [comment]
@MasterHans Can we solve this directly in the `CustomPages` module? So add and load your own stylesheet there?

**Comment by MasterHans** [comment]
> @MasterHans Can we solve this directly in the `CustomPages` module? So add and load your own stylesheet there?

Ok, I will do it. Thanks

**Comment by luke-** [comment]
Thanks then I close this one for now.

**Comment by luke-** [comment]
I think a simple CSS would be suffient.

**Pull request closed without merging**
