### PR TITLE
Apply image inline styles in email message

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/6639

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Thanks, this solution looks nice.

Can you please add tests for the different new features. (Attributes, E-Mail `max-widht`, ...)

**Comment by yurabakhtin** [comment]
> Can you please add tests for the different new features. (Attributes, E-Mail `max-widht`, ...)

@luke- Commit https://github.com/humhub/humhub/pull/6642/commits/1230cda47ef811be55df5f744d759c405d8a2184.

**Review by luke- — COMMENTED** [review]
@yurabakhtin Thanks, can you please separate the tests a bit, i.e. the height/width/position checks to  `RichTextHtmlConverterTest`.

Can you also test that the encoding of the description, height/width, etc. works correctly.

**Comment by yurabakhtin** [comment]
> Thanks, can you please separate the tests a bit, i.e. the height/width/position checks to `RichTextHtmlConverterTest`.
> 
> Can you also test that the encoding of the description, height/width, etc. works correctly.

Commit https://github.com/humhub/humhub/pull/6642/commits/72898a77c7c1f5a08680db8971c36d436e9a25c2 for `RichTextToEmailHtmlConverter`, but I don't see what new we can add for `RichTextHtmlConverterTest` because we have all tests here `protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextHtmlConverterTest.php`, I just fixed them here https://github.com/humhub/humhub/pull/6642/files#diff-777d9b242772f87b2dad26ac2cea0c878e2a5675f5e819061185e5f76a68e7f2.

**Review by luke- — APPROVED** [review]

**Pull request merged**
