### PR TITLE
Chg #7136: When opening a modal box, don't autofocus automatically on…

### PR DESCRIPTION
**Pull request by marc-farre**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Issue https://github.com/humhub/humhub/issues/7136

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@marc-farre Thanks, looks good for me!

- I think it would be good to add this change to the `MIGRATE-DEV.md` as well.
- Are there any important modals on the core or module side that need to be modified? e.g. `Space Invite` or `Create new Message`. It would be good if we could also add the `autofocus` here.

**Comment by marc-farre** [comment]
> change to the `MIGRATE-DEV.md` as well.

Yes, I was wondering if it was relevant for such minor changes, but you're right.
Done in commit https://github.com/humhub/humhub/pull/7137/commits/a6ced1e3445c502912c6c9a9b07a5401895468de

> `Space Invite`

The focus already was active, but there was a bug in the `humhub.ui.picker.js` file.
Fixed in commit https://github.com/humhub/humhub/pull/7137/commits/401d47bb11fcaa2e1ad654db6ee93908017a7ebd

> `Create new Message`

It was done here: https://github.com/humhub/humhub/pull/7137/files#diff-62f073854441a48c74ad57414fe23579a58f0e0a6e10fc323b38cf228b27b5d6R22
And in the Enterprise theme PR.

I had to add the focus feature to the `SpaceNameColorInput` class: https://github.com/humhub/humhub/pull/7137/files#diff-5067646a3d791b1d5e92b62736014fcd2565e8fd11516983778286d1911331cdR14

> Non-core module

I will take a look to all of them, but as there are many modal box, I might forget some. I'll do my best!

**Comment by luke-** [comment]
@marc-farre Thank you!

> > Non-core module
> 
> I will take a look to all of them, but as there are many modal box, I might forget some. I'll do my best!

The most important modules + ‘MIGRATE_DEV` will be sufficient. Thank you!

**Review by luke- — APPROVED** [review]

**Comment by marc-farre** [comment]
@luke- I reviewed all modules.

>  without increasing the minVersion.

Yes, except, except when adding autofocus to `SpaceNameColorInput` because I added the autofocus feature to the widget in the PR for HH 1.17.

That's why I had to increase the min version to 1.17 in the PR for the Enterprise Theme.
Other modules didn't need it.

**Pull request merged**
