### PR TITLE
Ada authentication

### PR DESCRIPTION
**Pull request by magwas**
This PR is meant as a preview of what I am working on.
It is functionally complete, but perhaps can be cleaned up.
Also contains a fix for AuthAction.php

Suggestions are welcome.

Makes possible to authenticate with Anonymous Digital Assurance http://adatom.hu/

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [X] All tests are passing
- [X] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by petrk94** [comment]
might I give my comment to this? Why a unknown SSO system which is only available in Hungarian, should be a major part of humhub? I even work on a identity system, but would rather implement in a fork instead of PR this to the main system.

**Comment by luke-** [comment]
Yes, maybe the best approach is to use the https://github.com/humhub/humhub-modules-devtools to create a small module and add this authentication class there.

This small module can also distributed to the module marketplace.

**Comment by magwas** [comment]
Thank you for your suggestions. Could you recommend a similar module to study to be able to do this?

**Comment by Felli** [comment]
@magwas I personally referenced the JWT module within the Enterprise module to create the [Discord Oauth](https://github.com/GreenMeteor/humhub-discord-module) module you can use this as a reference if you wish, although there are still some issues that have to be cleared up, it still works in the meantime. :yum:

**Pull request closed without merging**
