### PR TITLE
Brazilian Translation

### PR DESCRIPTION
**Pull request by Vamoss**

### CODE REVIEW

**Comment by luke-** [comment]
Please accept our CLA at: https://www.humhub.org/cla/github/sign

**Comment by luke-** [comment]
Sorry, there seems to be some conflicts with our http://translate.humhub.org site.
Can you resolve it?

**Comment by Vamoss** [comment]
Didn't find the conflict you are referring to, where can I find it inside the community? Thanks!

**Comment by luke-** [comment]
GitHub says:

We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

**Comment by programguy** [comment]
Is this the problem?
https://github.com/humhub/humhub/pull/593

**Comment by luke-** [comment]
I think the problem is that the translation was also made via translate.humhub.org - can you please "re" create a pull requests for missing translations?

**Pull request closed without merging**
