### PR TITLE
Enh/Fix: Cache Handling + File Preview Fix

### PR DESCRIPTION
**Pull request by Felli**
For better caching of commonly uploaded file types also added `Options +FollowSymLinks` to help fix some issues with file previews in some hosting environments.

### CODE REVIEW

**Comment by Felli** [comment]
Also thought of adding `Block bad bots` but there were a lot of entries and just didn't add it in. :thinking:

**Comment by Felli** [comment]
@danielkesselberg can you review this?

**Comment by Felli** [comment]
Have to find a working way of using `Content-Security-Policy` & `X-Frame-Options` (Most likely going to just drop the idea of `X-Frame-Options` altogether because it blocks all iframe even if ALLOWALL is given...)

**Comment by acs-ferreira** [comment]
IMHO, these options should not be sent by the framework/application itself, it could lead to a lot of problems.

These should be set **by the user** itself, if one has the knowledge to do so.

**Comment by danielkesselberg** [comment]
@Felli please split this pr. The Content-Security & X-Frame-Options is something else than the cache stuff.

**Comment by Felli** [comment]
@danielkesselberg I just didn't want to create too many p/r felt slightly lazy, but once I'm on my laptop I'll do that.
@acs-ferreira might be for the best to comment them out then. :thinking:

**Comment by Felli** [comment]
@danielkesselberg done.

**Comment by Felli** [comment]
I believe this applies for some dedicated Linux servers.

**Pull request merged**
