### PR TITLE
Enh #6164: Invitation by link

### PR DESCRIPTION
**Pull request by luke-**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Original: https://github.com/humhub/humhub/pull/6194#issuecomment-1507199987

### CODE REVIEW

**Comment by luke-** [comment]
@funkycram Can you please take a look into my commit? https://github.com/humhub/humhub/pull/6250/commits/52968c0edc6663795238ca8069925b49f2655f16 I've tried to migrate the logic a bit in service classes.

**Comment by funkycram** [comment]
> @funkycram Can you please take a look into my commit? [52968c0](https://github.com/humhub/humhub/commit/52968c0edc6663795238ca8069925b49f2655f16) I've tried to migrate the logic a bit in service classes.

@luke- Thanks a lot for this great refactoring!

I've committed a small fix: https://github.com/humhub/humhub/commit/06db70e728137a43bbd5ffcb4dcb82bbe918f475

I haven't finished all tests, but I've detected a small problem: If I register a new account from a Space link, I can create the account, but I'm not added to the related space.

When registering by Space link, the process is:
image
So the space ID is returned by the IdP (SSO provider) in the URL.

In my previous commits, the `AuthController::onAuthSuccess()` was creating the Invite record with the space ID from the URL:
image

But on your commit, this part seams to have been removed.
I'm not quite sure how to implement this, perhaps adding `LinkRegistrationService::convertToInvite()` in the `AuthController::onAuthSuccess()`, but I don't know if there is not a better method.

**Comment by luke-** [comment]
@funkycram Thanks for testing, indeed was this part missing. I've added it here: https://github.com/humhub/humhub/commit/ddae8a1778b5a8ba73c46f86159954d36c461e5e

**Comment by luke-** [comment]
@funkycram I have now changed from return params to session values to support auth clients like SAML. https://github.com/humhub/humhub/commit/2435e53a39f3b4fecc67a9dddd78bd628704392c

**Comment by funkycram** [comment]
> @funkycram I have now changed from return params to session values to support auth clients like SAML. [2435e53](https://github.com/humhub/humhub/commit/2435e53a39f3b4fecc67a9dddd78bd628704392c)

Thanks! Yes, I should have done it directly, also because I wasn't proud of my `$allAuthClientsCanSkipEmailValidation`!
I'll redo all tests tomorrow, thanks a lot for all your work to make the code much easier to understand, the methods where getting too long, but I did not dare to create additional classes (I should have!)

**Comment by luke-** [comment]
@funkycram Thank you. Originally I was also a bit worried about storing this in the session, but it's probably the best way. Yes, we are now trying to move more and more into service classes to better separate, maintain & test features.

**Comment by funkycram** [comment]
I've tested most common use cases (except LDAP), and everything's working fine now. Thanks a lot for finishing the code!

**Comment by funkycram** [comment]
@luke- can you merge this PR into develop?
I think we need it and it to have a full working invitation by link working with SSO.
Thanks!

**Comment by funkycram** [comment]
Thanks @luke- to a so quick merge! I'll do some testing again with this final version.

**Pull request merged**
