### PR TITLE
Hide "Like" link when no permission "Can like"

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Issue: https://github.com/humhub/humhub/issues/4743

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
A Like button still appears in my comments and sub-comments. Can you please check this again?

**Comment by yurabakhtin** [comment]
@luke- You wrote here https://github.com/humhub/humhub/pull/4747:

> A Like button still appears in my comments and sub-comments. Can you please check this again?

I have fixed this in commit https://github.com/humhub/humhub/pull/4747/commits/09b32c9270e315092fc1e5f77ba74de55ae159cc

The button was not hidden there because it is printed by separate code like `<?= LikeLink::widget(...) ?>` instead of event call, and this code is used in many other external modules. But please note in such cases the `LikeLink` often is used together with other links like `CommentLink`, e.g.:

```php
<?= LikeLink::widget(['object' => $gallery]) ?>
|
<?= CommentLink::widget(['object' => $gallery]) ?>
```

so if some link is hidden because of no permission then the separator `|` or `&middot;` is visible, so it looks not good I think.
If we need to display the separator  properly then it would be good to implement some new function like:

```php
<?= Widget::widgets([LikeLink::class, CommentLink::class], ['object' => $gallery, 'separator' => '|'])?>
```

Maybe a similar function already exists and if you know please tell me and let me know if we should fix the separator visibility in all modules.

**Comment by luke-** [comment]
We have something like this:

```php 
<?= \humhub\widgets\BaseStack::widget([
    'widgets' => [
        [
            CommentLink::class, ['object' => $comment], ['sortOrder' => 100],
            LikeLink::class, ['object' => $comment], ['sortOrder' => 200]
        ]
    ]
]);
```

But instead of using the BaseStack class directly, it would be good to create a new one like CommentEntryControls.

Hmm, since the PR is already a bit bigger as expected and the bug is not that critical, I would almost suggest to put it in the `Develop` branch. What do you think?

If we go the BaseStack widget way, we also have to move the canComment to the CommentLink widget here.

```php
//comment.php#90
        <div class="wall-entry-controls">
            <?php if ($module->canComment($comment)): ?>
                <?= CommentLink::widget(['object' => $comment]); ?>&nbsp;&nbsp;&middot;&nbsp;
            <?php endif; ?>
            <?= LikeLink::widget(['object' => $comment]); ?>
        </div>
```

**Comment by yurabakhtin** [comment]
@luke- 

> But instead of using the BaseStack class directly, it would be good to create a new one like CommentEntryControls.

I have reviewed all places and yes the `LikeLink::widget(...)` is used together with `CommentLink::widget()`, so yes we can new widget with name like `CommentEntryControls`, but please note the link widgets are used for different modules "wiki", "cfiles" and etc.

> Hmm, since the PR is already a bit bigger as expected and the bug is not that critical, I would almost suggest to put it in the Develop branch. What do you think?

I think the done fixes can be merged into `master` because they solve the visibility issue, but next the not urgent fix we can do in `develop` because it will just hide a separator between `LikeLink` and `CommentLink`.

> If we go the BaseStack widget way, we also have to move the canComment to the CommentLink widget here.

I see the `CommentLink` already has the restriction `canComment` inside.

**Comment by luke-** [comment]
Ok great! 

So you're going to do a separate PR for the CommentEntryControls?

**Comment by yurabakhtin** [comment]
@luke- Yes, we can do this in a separate PR for `develop`, I created the issue here: https://github.com/humhub/humhub/issues/4751.

**Review by luke- — APPROVED** [review]
OK, then I'll merge this PR into the Master Branch.

**Pull request merged**
