### PR TITLE
Fix #4614: Profile Image crop broken

### LINKED ISSUE #4614: Image editor issue in 1.7
### What steps will reproduce the problem?
Log into the HumHub Community. Go to your profile or a space you can change the picture of. Click the edit button on your profile image. Drag cropping handles.

### What is the expected result?
A new cropped portion of the image.

### What do you get instead?
A skewed, resized portion of the image. Saving the image results in a different view altogether.

### Additional info
Seems to affect banner images as well. I also noticed that certain images I upload appear distorted on my site, even though they worked fine on previous versions and I have not enabled compression.

### PR DESCRIPTION
**Pull request by buddh4**
Fixes https://github.com/humhub/humhub/issues/4614

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [x] No

### CODE REVIEW

**Comment by buddh4** [comment]
@sahartak2025 this reverts your changes from https://github.com/humhub/humhub/pull/4402 I've hidden the keymanager related radio, but could not recreate the overflow issue.

**Review by luke- — APPROVED** [review]

**Comment by ArchBlood** [comment]
@buddh4 you should just default to `width: 100%;` and not use `max-width: number_value%;`,  `max-width` is overly classified for this

**Comment by buddh4** [comment]
In this PR is set ` max-width: none;` since this fixes the issue.

**Comment by ArchBlood** [comment]
> In this PR is set ` max-width: none;` since this fixes the issue.

Just meant in general, `width: 100%` does the same thing for mobile and should also fix this issue as well, already tested this on my end with it working without fail

**Comment by buddh4** [comment]
I've tested `width:100%` and while it seems to work, the cropped image does not fit the actual selection. E.g. when cropping an very large banner image the crop result seems to be zoomed in immensly.

**Comment by buddh4** [comment]
Selection:

grafik

Result:

grafik

**Pull request merged**
