### PR TITLE
Fix migration on added duplicated container settings

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [ ] Changelog was modified

**Other information:**
https://github.com/humhub/humhub-internal/issues/246

### CODE REVIEW

**Comment by luke-** [comment]
@marc-farre FYI

**Comment by marc-farre** [comment]
Interesting, I wouldn't have thought about this eventuality, thanks for mentioning me.

@yurabakhtin Thanks for the fix!
Does it mean we should always check if the database is not already updated before applying a migration? E.g., if we add a column, we should check if it doesn't already exist?

**Comment by yurabakhtin** [comment]
> @yurabakhtin Thanks for the fix!
> Does it mean we should always check if the database is not already updated before applying a migration? E.g., if we add a column, we should check if it doesn't already exist?

@marc-farre Your change is not related to a creating of new column, there was an issue related to duplicated records with unique index, really it shouldn't have happened for a normal migration call, it seems it happened because 2 migration processes were called twice ata the same time, that should be fixed from core side, I will review the code soon.

However for adding new column we should use `humhub\components\Migration` and methods like `safeAddColumn()`, `safeCreateTable()` and etc. which already check it for existing before a creating, instead of `yii\db\Migration` and `addColumn()`.

**Comment by marc-farre** [comment]
@yurabakhtin Thanks. 

@luke- I've added @yurabakhtin recommendations in the doc via the PR https://github.com/humhub/documentation/pull/122

**Pull request merged**
