### PR TITLE
Hot fix for -- Rebuild group default Space Mapping #4586

### PR DESCRIPTION
**Pull request by MasterHans**
Changed m201025_095247_spaces_of_users_group.php migration
Deleted foreign key fk_group-space_id.
migrate-succesfully

### CODE REVIEW

**Comment by buddh4** [comment]
Now we get:
grafik

**Comment by buddh4** [comment]
@luke- do you think we need to align other parts as for example LDAP or MassUserImport.

**Comment by luke-** [comment]
@MasterHans Please see my update/commit. I think a TryCatch is easier here. Also, the FK should be automatically deleted by the databaseg when the field is deleted.

@buddh4 Good point, but should not affect the modules here. The modules do not change a group,  but only add members.

**Comment by MasterHans** [comment]
@buddh4  Something strange happened here can you please help to understand


test-error



error message in test

1) GroupTest: Single default spaces
Test ../../user/tests/codeception/unit/models/GroupTest.php:testSingleDefaultSpaces
Failed asserting that actual size 0 matches expected size 1.
#1 /home/runner/work/humhub/humhub/protected/humhub/modules/user/tests/codeception/unit/models/GroupTest.php:63

System try to run this test method
../../user/tests/codeception/unit/models/GroupTest.php:testSingleDefaultSpaces

But my branch ref_4586 does not contain this method - testSingleDefaultSpaces.

Looks like that in some how tests starting to run from the develop branch. And this error occurs.
I can not debug this error ...
What should I do ?
Add ../../user/tests/codeception/unit/models/GroupTest.php:testSingleDefaultSpaces to ref_4586 from develop branch?

**Comment by MasterHans** [comment]
> do you think we need to align other parts as for example LDAP or MassUserImport.

I think needed to find all mentioning of space_id and fix them....

**Comment by MasterHans** [comment]
> @buddh4 Good point, but should not affect the modules here. The modules do not change a group, but only add members.

Should I correct this module as well?

**Comment by MasterHans** [comment]
> @MasterHans Please see my update/commit. I think a TryCatch is easier here. Also, the FK should be automatically deleted by the databaseg when the field is deleted.

Ok I'll do it thanks

**Comment by MasterHans** [comment]
> Please see my update/commit. I think a TryCatch is easier here. Also, the FK should be automatically deleted by the databaseg when the field is deleted.

Done!

**Pull request merged**
