### PR TITLE
add table options for correct work with cyrillic

### PR DESCRIPTION
**Pull request by RichWeber**
+ add table options for correct work with cyrillic
+ added UA translations

### CODE REVIEW

**Comment by RichWeber** [comment]
there are some who live here?

**Comment by buddha87** [comment]
Hi sorry, you would overwrite translations of other languages. If you are interested in contributing in the translation of your language let me know, we have a community for tranlsation issues.

**Comment by RichWeber** [comment]
Yes, sure.
@buddha87 What do I have to do that you can accept my translation request?

**Comment by buddha87** [comment]
@RichWeber you can register under http://translate.humhub.org and join the space of your language, and do translations under the 'translation' menu item.

**Pull request closed without merging**
