### PR TITLE
Enh: Migrate phpspreadsheet 2.0

### LINKED ISSUE #6536: Export contact list to excel generates unreadable file
### What steps will reproduce the problem?

As an administrator go the contact list and click on the export button --> excel
image

The export to CSV functionality works.

The export to excel functionality does not.

When i export the contacts as excel i get an unreadable file (programs ask what encoding should be used to open the file)

### What is the expected result?

The excel file that downloads opens and displays the same info as the CSV 

### What do you get instead?

Excel file downloaded seems to be corrupt. (fixed size of 258kb vs 395kb for the CSV)

This used to work and seems was caused by an upgrade? Not sure which one though.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.3
| PHP version      |  8.2
| Operating system | linux

```
`$_GET = [
'r' => 'admin/user/export'
'format' => 'xlsx'
]

$_SERVER = [
'TEMP' => '/home/clients/xxx/tmp'
'TMPDIR' => '/home/clients/xxx/tmp'
'TMP' => '/home/clients/xxx/tmp'
'ORIG_SCRIPT_NAME' => '/.fpm/php5.external'
'ORIG_PATH_TRANSLATED' => '/home/clients/xxx/index.php'
'ORIG_PATH_INFO' => '/index.php'
'ORIG_SCRIPT_FILENAME' => '/home/clients/xxx/.fpm/php5.external'
'SCRIPT_NAME' => '/index.php'
'REQUEST_URI' => '/index.php?r=admin%2Fuser%2Fexport&format=xlsx'
'QUERY_STRING' => 'r=admin%2Fuser%2Fexport&format=xlsx'
'REQUEST_METHOD' => 'GET'
'SERVER_PROTOCOL' => 'HTTP/1.1'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'REDIRECT_QUERY_STRING' => 'r=admin%2Fuser%2Fexport&format=xlsx'
'REDIRECT_URL' => '/index.php'
'REMOTE_PORT' => '38790'
'SCRIPT_FILENAME' => '/home/clients/xxx/index.php'
'SERVER_ADMIN' => 'xxx'
'CONTEXT_DOCUMENT_ROOT' => '/home/clients/xxx/.fpm/'
'CONTEXT_PREFIX' => '/.fpm/'
'REQUEST_SCHEME' => 'https'
'DOCUMENT_ROOT' => 'xxxx'
'REMOTE_ADDR' => 'xx'
'SERVER_PORT' => '443'
'SERVER_ADDR' => '127.0.0.80'
'SERVER_NAME' => 'intranet.xxx.xx'
'SERVER_SOFTWARE' => 'Apache'
'SERVER_SIGNATURE' => ''
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_COOKIE' => 'xxxxxxx'
'HTTP_HOST' => 'xxx.xx'
'HTTP_TE' => 'trailers'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_SEC_FETCH_MODE' => 'same-origin'
'HTTP_SEC_FETCH_DEST' => 'empty'
'HTTP_REFERER' => 'https://intranet.xxx.xx/index.php?r=admin%2Fuser%2Flist'
'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5'
'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0'
'PHP_VERSION' => '8.2'
'SCRIPT_URI' => 'https://intranet.xxx.xx/index.php'
'SCRIPT_URL' => '/index.php'
'HTTPS' => 'on'
'UNIQUE_ID' => 'xxx'
'REDIRECT_STATUS' => '200'
'REDIRECT_HANDLER' => 'php5-fcgi'
'REDIRECT_PHP_VERSION' => '8.2'
'REDIRECT_SCRIPT_URI' => 'https://intranet.xxx.xx/index.php'
'REDIRECT_SCRIPT_URL' => '/index.php'
'REDIRECT_HTTPS' => 'on'
'REDIRECT_UNIQUE_ID' => 'XXX'
'FCGI_ROLE' => 'RESPONDER'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 1693775149.9046
'REQUEST_TIME' => 1693775149
] `
```

### LINKED ISSUE #6975: Migrate phpspreadsheet version
### Is your feature request related to a problem? Please describe.
#6536 causes issues due to outdated version of the phpspreadsheet library

### Describe the solution you'd like
We should migrate from using `^1.0` to `^2.0` instead

### Describe alternatives you've considered
I see no other options available at this time.

### PR DESCRIPTION
**Pull request by ArchBlood**
**What kind of change does this PR introduce?** (check at least one)
fixes #6975 
fixes #6536 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [x] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ArchBlood** [comment]
Currently not able to fix the test.

**Comment by ArchBlood** [comment]
Seems like the only part that didn't pass was the `composer.json`, everything else works as intended, if any changes need made just ask @luke-.

**Comment by luke-** [comment]
@ArchBlood It would be good if you could commit the modified `composer.lock` as well, so that the tests run through.

Also, if changes to modules are necessary, it would be good if you could also adapt the `MIGRATE-DEV.md`.

Thanks!

**Comment by ArchBlood** [comment]
Currently the only module(s) that I know of that use the `SpreadsheetExport` class directly is the Calendar module, but I also see that the tasks module uses PhpSpreadsheet, I haven't tested possible changes needed here.

### Tasks Module
https://github.com/humhub/tasks/blob/25c18da9ee5e061569067925f21b1ab3ffad1317/traits/DataExport.php#L7-L8
- https://github.com/PHPOffice/PhpSpreadsheet/blob/2.0.0/src/PhpSpreadsheet/Style/NumberFormat.php
- https://github.com/PHPOffice/PhpSpreadsheet/blob/2.0.0/src/PhpSpreadsheet/Shared/Date.php

### Calendar Module
https://github.com/humhub/calendar/blob/master/models/participation/CalendarEntryParticipation.php#L385

**Comment by luke-** [comment]
@ArchBlood If it has an impact on modules, I would merge the PR in the next release 1.17.

If the modules such as calendar/tasks work without migration, we can still integrate it into 1.16.

Can you please test this?

Thanks!

**Review by yurabakhtin — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
