### PR TITLE
Hashtags

### PR DESCRIPTION
**Pull request by zhelyabuzhsky**
Hashtag function for feature request #431

### CODE REVIEW

**Comment by Lokyaziis** [comment]
Post block on creation (infinite 3 points loader)!! But the post is created cause when I refresh the page the post is here with the hashtag... clicking on the hashtag link to a result page with some direct code on the left ({n, plural, =1{Found {n, number} post} =other{Found {n, number} posts}}) and no results... (doesn't found nothing) !! And as a french user, it created hashtag with all word with ' , Such as " l%#38amour" instead of "l'amour" !!

**Comment by gigabytedevelopers** [comment]
Please can someone send me the table hashtag_post from their database, I have even tried the yii migration tool but the table has not been created in my database.. I need it, please.

**Comment by b17** [comment]
@gigabytedevelopers Try this command to execute migrations:
```
./yii help migrate --includeModuleMigrations
```

**Comment by luke-** [comment]
It's planned to add some topic feature to the 1.3 - since this solution is only for Posts we can't merge it to the core.

We need something more flexible for Content and also maybe Users & Spaces.

**Pull request closed without merging**
