### PR TITLE
Support PHP 8.1

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [ ] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5552

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Any idea regarding the failing tests?

**Comment by yurabakhtin** [comment]
@luke- 

> Any idea regarding the failing tests?

I think the problem in the file https://github.com/php-imagine/Imagine/blob/develop/src/Image/Metadata/MetadataBag.php as I described here https://github.com/humhub/humhub/issues/5552#issuecomment-1046757723

**Comment by luke-** [comment]
@yurabakhtin Hmm, I don't think it's related to Imagine. (Maybe to the `serialze` change?)  Otherwise I would merge it now and wait until Imagine provides an updated version.

**Comment by yurabakhtin** [comment]
@luke- 

> There are no failing 8.1 tests.

Ah if I need to fix tests for other PHP versions < 8.1 then I will review them again. But why don't I see tests for php 8.1 in this PR when here https://github.com/humhub/humhub/pull/5561/files#diff-acf3e0c6c881e3230ee20ea7499891845048d94362e17e496f06dafa7757f110R32 it is not disabled?

**Comment by luke-** [comment]
@yurabakhtin No idea. i had added and removed PHP 8.1 on `develop` in the meantime. Possibly GitHUb action got mixed up here and still goes from the Develop Branch.

**Review by luke- — APPROVED** [review]

**Pull request merged**
