### PR TITLE
Limit jQuery with version < 3.7.0 to avoid dropdown error

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/6666

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Any idea regarding the failing tests?

**Comment by yurabakhtin** [comment]
@luke- 

> Any idea regarding the failing tests?

yes strange error becuase all tests were stoped on step:

```
Run actions/setup-node@v1
Error: Unable to find Node version '10.x' for platform linux and architecture x64.
```

after re-run tests the step is executed without error but all acceptance tests have error:

```
  [Facebook\WebDriver\Exception\SessionNotCreatedException] Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
```

Locally it works. Maybe chromedriver should be updated there.

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look again? I've updated the selenium driver, it now uses the same as master, without errors.

**Comment by yurabakhtin** [comment]
> Can you please take a look again? I've updated the selenium driver, it now uses the same as master, without errors.

@luke- I see your solution `:117.0-20230926` fixed the tests, but then after merging of `master` I see an error in the test `AutoTourCest` that is strange because locally it works without errors.

**Comment by luke-** [comment]
@yurabakhtin I did the same on the `master` branch and it doesn't fail: https://github.com/humhub/humhub/commit/0f25e4b8fab71e4c4d10f9138e283bcee5411e31

**Comment by yurabakhtin** [comment]
> @yurabakhtin I did the same on the `master` branch and it doesn't fail: [0f25e4b](https://github.com/humhub/humhub/commit/0f25e4b8fab71e4c4d10f9138e283bcee5411e31)

@luke- hm, very strange behaviour with tests... no idea yet.

**Comment by luke-** [comment]
@yurabakhtin Hmm, on my local environment I can reproduce this error even without your PR. I've added a 'skip' for this tests and created an new issue for this.

How do you run the test? 

With the single test command ` cd $HUMHUB_PATH/protected/humhub/modules/tour/tests; $HUMHUB_VENDOR_BIN/codecept run codeception/acceptance/AutoTourCest.php` ?

My new issue is here: https://github.com/humhub/humhub/issues/6678

**Comment by yurabakhtin** [comment]
> How do you run the test?
> 
> With the single test command ` cd $HUMHUB_PATH/protected/humhub/modules/tour/tests; $HUMHUB_VENDOR_BIN/codecept run codeception/acceptance/AutoTourCest.php` ?

@luke- yes, with the single run `codeception run acceptance:AutoTourCest`.

> My new issue is here: #6678

ok.

**Pull request merged**
