### PR TITLE
Optimize notification overview

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
https://github.com/humhub/humhub-internal/issues/89

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Can you please rebase? Sorry for the late merge.

**Comment by yurabakhtin** [comment]
> Can you please rebase? Sorry for the late merge.

@luke- I have merged `develop` into this PR but please wait tests before merging.

**Comment by luke-** [comment]
@yurabakhtin Tests looks good. Merge?

**Comment by yurabakhtin** [comment]
> @yurabakhtin Tests looks good. Merge?

@luke- Yes, you can merge because UI side looks correctly for the PR.

**Review by luke- — APPROVED** [review]

**Pull request merged**
