### PR TITLE
Fix for Delete stream entry in permalink view

### LINKED ISSUE #2912: Delete stream entry in permalink view
### What steps will reproduce the problem?

1. Enter a permalink of a post
2. Delete this post by means of the stream entry dropdown

### What is the expected result?

-  The stream should be reloaded with all remaining entries with an success message.

### What do you get instead?

- An empty stream message

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2

### PR DESCRIPTION
**Pull request by githubjeka**
fix #2912

### CODE REVIEW

**Comment by Felli** [comment]
Doesn't fully reload for me :thinking:

screenshot_1

**Comment by githubjeka** [comment]
Try delete all assets and check DEV env

**Comment by Felli** [comment]
Works on dev, not production but doesn't truly reload should think about using `.empty()` or `.remove()` for content deletion. :thinking:

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/f385e0cd5d829743ddc297c784434786ee25e5b5

**Pull request closed without merging**
