### PR TITLE
FormModal example

### PR DESCRIPTION
**Pull request by luke-**

### CODE REVIEW

**Comment by luke-** [comment]
@marc-farre A quick idea. What do you think?
 
We may could also add the "[begin|end]FormModal" methods directly to `humhub\widgets\modals\Modal`.

**Comment by marc-farre** [comment]
@luke- Thanks!
Yes, that will help.
But as the new widget only has 2 methods, I think I we could avoid adding a new one (we already have lots of widgets) and add these 2 methods directly into `humhub\widgets\modals\Modal` as you also suggest.
I think it also makes things clearer, because without reading the code, we don't know if `FormModal` extends `Modal` or `ActiveForm` widget.

**Comment by luke-** [comment]
@marc-farre Good point.

I've adjusted the PR. Should we want to introduce this or stay with the current way?

**Comment by marc-farre** [comment]
Thanks! Yes, I think it's better to use these 2 new methods.
I will take care of it to finish migrating all existing Modals with forms, and updating the doc.
I will then merge the PR.

**Pull request merged**
