### PR TITLE
Show cron times in "Email Summaries" settings

### PR DESCRIPTION
**Pull request by dantefromhell**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Our users found the information when email summaries are scheduled very helpful to understand their choice better.

### CODE REVIEW

**Comment by ArchBlood** [comment]
Here's a modified version to this;
```php
    /**
     * Returns a list of available mail summary intervals with their corresponding times
     *
     * @return array the intervals with times
     */
    public function getIntervals()
    {
        $serverTimeZone = Yii::$app->settings->get('timeZone');
        $dailyCronTime = Yii::$app->params['dailyCronExecutionTime'] . ' (' . $serverTimeZone . ')';
        $weeklyCronDays = date('l', static::getModule()->weeklySummaryDay) . 's';

        return [
            MailSummary::INTERVAL_NONE => Yii::t('ActivityModule.base', 'Never'),
            MailSummary::INTERVAL_HOURLY => Yii::t('ActivityModule.base', 'Hourly'),
            MailSummary::INTERVAL_DAILY => Yii::t('ActivityModule.base', 'Daily - send at {time}', ['time' => $dailyCronTime]),
            MailSummary::INTERVAL_WEEKLY => Yii::t('ActivityModule.base', 'Weekly - send on {days} at {time}', ['days' => $weeklyCronDays, 'time' => $dailyCronTime]),
        ];
    }
```
Screenshot_1

But my preferred way of doing this would be the following;
```php
/**
 * Returns a list of available mail summary intervals with their corresponding times
 *
 * @return array the intervals with times
 */
public function getIntervals()
{
    $currentTimestamp = new \DateTime('now', new \DateTimeZone(Yii::$app->settings->get('timeZone')));

    // Calculate different times for each interval
    $hourlyTime = clone $currentTimestamp;
    $hourlyTime->modify('+1 hour');

    $dailyTime = clone $currentTimestamp;
    $dailyTime->modify('+1 day');

    $weeklyTime = clone $currentTimestamp;
    $weeklyTime->modify('+1 week');

    $format = 'H:i:s T'; // Adjust the format based on your preferences

    return [
        MailSummary::INTERVAL_NONE => Yii::t('ActivityModule.base', 'Never'),
        MailSummary::INTERVAL_HOURLY => Yii::t('ActivityModule.base', 'Hourly')  . ' - ' . $hourlyTime->format($format),
        MailSummary::INTERVAL_DAILY => Yii::t('ActivityModule.base', 'Daily')  . ' - ' . $dailyTime->format($format),
        MailSummary::INTERVAL_WEEKLY => Yii::t('ActivityModule.base', 'Weekly') . ' - ' . $weeklyTime->format($format),
    ];
}
```
Screenshot_2

The first is recommended over the second one though.

**Comment by ArchBlood** [comment]
Also in `MailSummary.php` I think the following should be changed @luke-;
https://github.com/humhub/humhub/blob/420a5541d947f52f5b365a5e161c1f55a71f28b0/protected/humhub/modules/activity/components/MailSummary.php#L193-L208

```php
    /**
     * Returns the last summary date
     *
     * @return string of the last summary mail date
     */
    protected function getLastSummaryDate(): string
    {
        $lastSent = (int) static::getModule()->settings->user($this->user)->get('mailSummaryLast');

        if (empty($lastSent)) {
            // Default to 24 hours ago if not set
            $currentDateTime = new \DateTime();
            $currentDateTime->sub(new \DateInterval('PT24H'));
            $lastSent = $currentDateTime->format('Y-m-d G:i:s');
        } else {
            $lastSent = date('Y-m-d G:i:s', $lastSent);
        }

        return $lastSent;
    }
```

**Comment by dantefromhell** [comment]
> Also in MailSummary.php I think the following should be changed @luke-;

Yes I was about to file an issue for this, thx for the catch

> But my preferred way of doing this would be the following;

If I understand your code correctly this will always show the next execution, right?

If so we didnt find it as useful as describing the pattern by which email summaries will be send.

**Comment by ArchBlood** [comment]
> > Also in MailSummary.php I think the following should be changed @luke-;
> 
> Yes I was about to file an issue for this, thx for the catch
> 
> > But my preferred way of doing this would be the following;
> 
> If I understand your code correctly this will always show the next execution, right?
> 
> If so we didnt find it as useful as describing the pattern by which email summaries will be send.

The first should show the same as in your code, the only difference is it's done in a slight more maintainable way.

Another option would be this, which is more maintainable, but increases the size and more to be maintained;
```php
/**
 * Returns a list of available mail summary intervals with their corresponding times
 *
 * @return array the intervals with times
 */
public function getIntervals()
{
    return [
        MailSummary::INTERVAL_NONE => $this->getNeverInterval(),
        MailSummary::INTERVAL_HOURLY => $this->getHourlyInterval(),
        MailSummary::INTERVAL_DAILY => $this->getDailyInterval(),
        MailSummary::INTERVAL_WEEKLY => $this->getWeeklyInterval(),
    ];
}

/**
 * Get the interval string for "Never"
 *
 * @return string the "Never" interval string
 */
private function getNeverInterval()
{
    return Yii::t('ActivityModule.base', 'Never');
}

/**
 * Get the interval string for "Hourly"
 *
 * @return string the "Hourly" interval string
 */
private function getHourlyInterval()
{
    return Yii::t('ActivityModule.base', 'Hourly');
}

/**
 * Get the interval string for "Daily"
 *
 * @return string the "Daily" interval string
 */
private function getDailyInterval()
{
    $dailyCronTime = $this->getCronTimeString(Yii::$app->params['dailyCronExecutionTime']);
    return Yii::t('ActivityModule.base', 'Daily - send at {time}', ['time' => $dailyCronTime]);
}

/**
 * Get the interval string for "Weekly"
 *
 * @return string the "Weekly" interval string
 */
private function getWeeklyInterval()
{
    $weeklyCronDays = date('l', static::getModule()->weeklySummaryDay) . 's';
    $dailyCronTime = $this->getCronTimeString(Yii::$app->params['dailyCronExecutionTime']);
    return Yii::t('ActivityModule.base', 'Weekly - send on {days} at {time}', ['days' => $weeklyCronDays, 'time' => $dailyCronTime]);
}

/**
 * Get the formatted cron time string
 *
 * @param string $time The cron execution time
 * @return string the formatted cron time string
 */
private function getCronTimeString($time)
{
    $serverTimeZone = Yii::$app->settings->get('timeZone');
    return $time . ' (' . $serverTimeZone . ')';
}
```

**Comment by ArchBlood** [comment]
@dantefromhell why close this, it should be encouraged to be implemented for better understanding.

**Comment by dantefromhell** [comment]
Oops, I didnt realize there was a PR in my humhub fork when I deleted the repo.

Not sure how this PR can be made actionable again, there's a bunch of possibilities listed here, but which is the best way forward?

**Comment by ArchBlood** [comment]
> Oops, I didnt realize there was a PR in my humhub fork when I deleted the repo.
> 
> Not sure how this PR can be made actionable again, there's a bunch of possibilities listed here, but which is the best way forward?

Me personally I'd probably go with https://github.com/humhub/humhub/pull/6804#issuecomment-1897676573 for readability.

**Pull request closed without merging**
