### PR TITLE
File dropdown not visible at the bottom of the page

### PR DESCRIPTION
**Pull request by marc-farre**
- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Issue: https://github.com/humhub/mail/issues/357

### CODE REVIEW

**Comment by luke-** [comment]
@marc-farre Thanks for the PR. Shouldn't we merge this into the 'master' branch?

**Comment by marc-farre** [comment]
> @marc-farre Thanks for the PR. Shouldn't we merge this into the 'master' branch?

Yes, I thought about it, I was unsure. Are you doing it or should I create a new PR (or update this one) based on Master?

**Comment by luke-** [comment]
@marc-farre It would be good if you could do that. Unfortunately I can't do a rebase because of the "CHANGELOG-DEV" change.

**Comment by marc-farre** [comment]
Done: https://github.com/humhub/humhub/pull/6647

**Pull request closed without merging**
