### PR TITLE
Actually cache $_moduleInfo

### PR DESCRIPTION
**Pull request by martin-rueegg**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfils these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing -> behaviour does not change
- [ ] New/updated tests are included -> behaviour does not change
- [ ] Changelog was modified -> Which changelog?

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Please let me know if I should consider/fix something in my code or where I should add this to a change log. Thank you!

### CODE REVIEW

**Comment by ArchBlood** [comment]
Could you provide a little more information on which part (if any) of the the `$_moduleInfo` that isn't cached?

**Comment by luke-** [comment]
@martin-rueegg Thanks for the fix!

@ArchBlood Seems we don't set the `_moduleInfo` attribute at all.

**Review by luke- — APPROVED** [review]

**Comment by ArchBlood** [comment]
@luke- just wondering if this would be a better solution;

```php
    /**
     * Reads module.json which contains basic module information and
     * returns it as array
     *
     * @return array module.json content
     */
    protected function getModuleInfo(): ?array
    {
        if ($this->_moduleInfo !== null) {
            return $this->_moduleInfo;
        }
        $moduleJson = file_get_contents($this->getBasePath() . DIRECTORY_SEPARATOR . 'module.json');

        return $this->_moduleInfo = Json::decode($moduleJson);
    }
```
This way you don't have to change `$_moduleInfo` itself and still caches the modules installed.

**Comment by luke-** [comment]
@ArchBlood Hmm, I would prefer both, adding a return type to the method and add the type to the attribute.

**Comment by martin-rueegg** [comment]
I haven't added the return type to the method in order not to break backwards compatibility, as any deriving class would have to adapt to the new interface ...

But it seems there is a bit of inconsistency throughout the project as to where return types are used and where not.

**Comment by luke-** [comment]
@martin-rueegg Yes, we try to add this to new methods. Maybe we can refactor a larger part automatically with tools like Rector.

**Comment by martin-rueegg** [comment]
@luke- Well, refactoring can also be done with IDEs like PhpStorm. I don't see the issue within the core code. However, you will still break backwards-compatibility as modules that extend such a modified class will no longer compile.

**Pull request merged**
