### PR TITLE
Use https for sample OEmbed endpoints

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/4714

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
Can you please put the PR for this critical bug directly against the Master Branch? Probably a new PR is easier because of the change to CHANGELOG_DEV.md. Otherwise it is so good!

**Comment by yurabakhtin** [comment]
@luke- hmm, I changed the base from `develop` to `master`, so now you can see "Files changed (364)" because the branch `fix/4714-youtube-oembed-not-working` was created from `develop`. Does it mean I should create a new branch from `master` with same changes and then create new PR from that new branch?

**Comment by luke-** [comment]
Yes, I think it's easier to create a new branch based on master.

**Comment by luke-** [comment]
I think it has something to do with CHANGELOG_DEV.md, which does not exist in the master.

**Pull request closed without merging**
