### PR TITLE
Enh #3506: Add Open Graph support to have preview of the pages on oth…

### PR DESCRIPTION
**Pull request by marc-farre**
Enh #3506: Add Open Graph support to have preview of the pages on other websites (Facebook, Twitter, etc.)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ArchBlood** [comment]
Love the idea, but I'm wondering why the Post controller instead of the content container controller, wouldn't doing this make it more globalized?

**Comment by funkycram** [comment]
> why the Post controller instead of the content container controller, wouldn't doing this make it more globalized?

Because we need the Post object (after find in the database) to get the title, message and image metadatas for the preview.
In the Content Container controller, we don't know which is the content.

**Comment by funkycram** [comment]
About the failing checks:
✖ ChangeEmailCest: Ensure that changing email works
E InviteCest: Ensure that inviting external users by mail form works.
✖ PasswordRecoveryCest: Ensure that password recovery works
S ProfileCest: Ensure that saving the account works 
E NonceCest: Test statistic
E NonceCest: Test invalid statistic

I tested changing email, inviting, password recovery and profile saving: I had no error and it worked properly with Humhub 1.12.1.
I could not understand what is the problem. I didn't test the NonceCest error.

**Comment by luke-** [comment]
@funkycram Thanks for the feature PR! 

FYI: I'm in the process of restructuring your PR a bit. Mainly that the complete meta handling sits in its own class. The current `View` class is already very large and I want to keep it as lean as possible.

Another point:  The `humhub\modules\web\pwa\widgets\LayoutHeader` is actually only for the PWA specific things and can be disabled if necessary.

See my copy of your PR here: https://github.com/humhub/humhub/pull/5868/files

**Comment by funkycram** [comment]
Thanks @luke- , it's much better yes to separate the meta part in another class.
Then we need controllers to be able to set metadata, such as [the PostController](https://github.com/humhub/humhub/pull/5863/files#diff-d47476863657fd72e21ff4461f800efee7289a4c8641efa9f3169c65a39da4b6).
Perhaps we could add `View::setMeta()` method?

Should I merge your PR and finish the work or did you plan to do it?
Thanks.

**Comment by luke-** [comment]
@funkycram I'm considering finishing implementing it. Currently I'm thinking about how to improve the API for the PostController (and other content controllers).

Post Controller:

```php 
$this->view->meta->setContent($post);  // For ContentContainer / Author Infos / Date Infos
$this->view->meta->setTitle($post->getOwner()->getDisplayName()); // The Container Name should be automatically appended
$this->view->meta->setDescription(RichText::convert($post->message, RichText::FORMAT_SHORTTEXT)); // Truncate by `ViewMeta`
$this->view->meta->setImage($post->fileManager->findAll()); // Auto select first image from result set
``` 
What do you think about such an API?

---
Often I see the problem, for example, when I paste from the intranet into Link in another software, that Opengraph/Meta does not work, because the meta data for the login page is displayed. e.g. https://stackoverflow.com/questions/23695745/how-to-serve-opengraph-for-a-private-page

Unfortunately, if we also want to solve this problem, it becomes more complicated. 

We somehow need to (if enabled) resolve the meta data before the permission "loginRequired" redirect and cache it to display it later on the login page.

Should we take that into consideration?  

This would definitely have to become an optional feature (and not active by default), since private information is partially accessible without a login.

**Comment by funkycram** [comment]
> I'm considering finishing implementing it.
Thanks a lot!

> API for the PostController
I don't have enough experience with the API to be able to answer, but it looks good.
For the title, perhaps we could add the name of the container (e.g. the space name): `$post->getOwner()->getDisplayName() . ' · ' . $post->content->container->getDisplayName();`

About the contents of Humhubs not allowing guest access (and only in this case), indeed the login page is displayed. For other Humhubs, private contents return 404 Not found (or 401 Unauthorized if the Space is not public for guests).
In my opinion, ideally, for Humhubs not allowing guest access, content metatags for OpenGraph should give any information about the content (as the platform is private), but could be:
- Title: Name of the application
- Description: Empty
- Image: the logo of the application

If you think this is a good option, then we only need to set the meta title in [AuthController::actionLogin()](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AuthController.php#L93).

Now, my answer is different for internal links (links from the same Humhub instance), with the [LinkPreview](https://www.humhub.com/en/marketplace/linkpreview/) module: if think this is a problem that could be solved by the module, but ideally, the preview should work even if the Humhub is not allowing guest access.

Thanks again for this work!

**Comment by luke-** [comment]
@funkycram Thanks, merged https://github.com/humhub/humhub/pull/5868 based on your work. Feel free to enhance if required.

**Comment by funkycram** [comment]
> @funkycram Thanks, merged #5868 based on your work. Feel free to enhance if required.

Thanks a lot @luke- !

**Pull request closed without merging**
