### PR TITLE
Enh #5144: Show sort order in profile fields settings

### PR DESCRIPTION
**Pull request by funkycram**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [X] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [X] All tests are passing
- [X] New/updated tests are included
- [X] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@funkycram Can you please check our CLA?
https://cla-assistant.io/humhub/humhub?pullRequest=5147

**Comment by funkycram** [comment]
CLA accepted

**Comment by luke-** [comment]
@funkycram can you please check again? 
https://github.com/humhub/humhub/pull/5147#issuecomment-870408954

**Comment by funkycram** [comment]
Just done. There seems to be a problem with theses CLA as this is the 3rd time I accept them.

**Comment by ArchBlood** [comment]
This is the root cause, the pr involves a "ghost" user and all parties must sign the CLA before it's marked as signed @luke- 
https://github.com/humhub/humhub/commit/78704f0fd061e14d5031544d06a110ae45f9ef0a

**Comment by funkycram** [comment]
If I understand well, the problem is that my email was not assigned to my commit. Now my email is well assigned to GIT on my computer. So I think that I must close this commit and PR and create a new one. Do you confirm?

**Comment by ArchBlood** [comment]
> If I understand well, the problem is that my email was not assigned to my commit. Now my email is well assigned to GIT on my computer. So I think that I must close this commit and PR and create a new one. Do you confirm?

That should do it, as long as your GIT and GitHub account has the same email it should then reflect right, I'm not much of a GIT expert when it comes to or pushing, just noticed that when using CLAassistant it can be a little underwhelming at times and requires all parties (emails assigned to a Github account) to verify 😄

**Review by luke- — APPROVED** [review]

**Pull request merged**
