### PR TITLE
Auto enable "Hide file info (name, size) for images on wall" option

### PR DESCRIPTION
**Pull request by sahartak2025**

### CODE REVIEW

**Comment by Carl2213** [comment]
Can you add a provision for choosing file types as well? This would make it possible to customize for videos and other file types that aren't supposed to be downloadble.

**Comment by luke-** [comment]
@Carl2213 Currently this is probably realized by a query of the mime category 'image/*'. I don't know whether we should make this configurable as a module attribute.

**Comment by Carl2213** [comment]
It doesn't need to be configurable via GUI, but being configurable at all would be nice.

**Review by luke- — APPROVED** [review]

**Comment by buddh4** [comment]
@Carl2213 can you open a feature request issue for this (if not already done). Perhaps this could be done as stream module class configuration.

**Pull request merged**
