### PR TITLE
Add content id in the file table

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5522

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Thanks, can you please check if we get this set somehow in files of comments?

**Comment by yurabakhtin** [comment]
@luke- I found a quick solution for the bug above: if I revert the commit https://github.com/humhub/humhub/commit/18ec9a3 , do you remember why you did this?

Currently the problem in that if we call there `$this->save()` then the code `File->beforeNewStoredFile()` is called twice where the code line `$this->store->delete(null, [FileHistory::VARIANT_PREFIX . '*']);` deletes the file what is uploaded on first call of the `File->save()`.

It seems you wanted to update some info in the table `file` that is updated only on call the `File->save()`.

**Comment by luke-** [comment]
@yurabakhtin - I made the change to update columns like "updated_at" and "updated_by". Do you think I should find another solution here?

- About comments: When a file is added to a comment, the "content_id" should be set here as well. A comment is always assigned to a content. (The migration should also take this into account)

**Comment by yurabakhtin** [comment]
@luke- 

> I made the change to update columns like "updated_at" and "updated_by". Do you think I should find another solution here?

It seems you didn't see my updated text in the comment above:

> I fixed the bug in PR https://github.com/humhub/humhub/pull/5593 without touching your code, so all columns are updated as before.

So you shouldn't find a solution, it was already done, i.e. the fields `updated_at` and `updated_by` are updated as expected.

**Comment by luke-** [comment]
@yurabakhtin Thanks! Can you please check the migration as well? That existing comment files are also assigned to a content ID?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please check the migration as well? That existing comment files are also assigned to a content ID?

Done in commit https://github.com/humhub/humhub/pull/5583/commits/e12c30373b7f08dc1ba50826518d56c1cb8950d4.

**Review by luke- — APPROVED** [review]

**Pull request merged**
