### PR TITLE
Fix profile field value result type

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [ ] Changelog was modified

**Other information:**
Issue: https://community.humhub.com/s/announcements/?contentId=247573&commentId=39511

### CODE REVIEW

**Comment by ArchBlood** [comment]
@yurabakhtin sadly this does not fix this if in PeopleDetails has the `gender` field selected.

**Comment by yurabakhtin** [comment]
@ArchBlood Sorry, but I cannot reproduce this:

test_gender_people

**Comment by ArchBlood** [comment]
> @ArchBlood Sorry, but I cannot reproduce this:
> 
> test_gender_people

See the full screenshot on which fields are filled, if a specific user group is used along with the `gender` profile field is used the error is thrown, at least for me, and it reports that the issue is with `PeopleDetails.php`
https://community.humhub.com/comment/perma?id=39512

**Comment by ArchBlood** [comment]
Tested with PHP 7.4 and 8.0.9

**Comment by luke-** [comment]
Can you provide steps to reproduce?

**Comment by ArchBlood** [comment]
> Can you provide steps to reproduce?

Update by the Updater module then fill out the PeopleDetails form as shown on the linked reply after manually applying this fix which then returns the following error due to the `gender` profile field, I would of course provide more information but our site overseer has taken Green Meteor down.

```log
TypeError: Return value of humhub\modules\user\models\ProfileField::getUserValue() must be of the type string, null returned in /home/USER/www/protected/humhub/modules/user/models/ProfileField.php:313
```

**Comment by luke-** [comment]
@ArchBlood Oh, hope GM will be released soon. I think already that the merge fixes the problem and with the beta.2 upgrade path will be adjusted.

**Comment by ArchBlood** [comment]
> @ArchBlood Oh, hope GM will be released soon. I think already that the merge fixes the problem and with the beta.2 upgrade path will be adjusted.

I hope so as well, what's left of the team wants to continue working on the HumHub module development side of things we just have to change a lot of things before we can fully restart everything, once we've worked everything out we'll look back into this issue 🤔

**Comment by luke-** [comment]
All the best to you & team!

**Pull request merged**
