### PR TITLE
Test Disable Login Form

### PR DESCRIPTION
**Pull request by luke-**
Related: https://github.com/humhub/humhub/issues/6780#issuecomment-1881296805

configuration file example
```php
return [
    'container' => [
        'definitions' => [
            \humhub\modules\user\controllers\AuthController::class => [
                'showLoginForm' => false,
                'allowUserRegistrationFromAuthClientIds' => ['keycloak', 'saml']
            ]
        ]
    ]
];
```

### CODE REVIEW

**Comment by marc-farre** [comment]
Thanks very much @luke- !
It works fine and will be very helpful.

What about also adding the `showRegistrationForm` param?
It would allow removing whats in the pink rectangles (we also should remove the "or" horizontal line):

image

image

image

If it helps, I can contribute with a commit for this in a few days.

**Comment by luke-** [comment]
@marc-farre I have added a `showRegistrationForm` variable. Do we need to show the `AuthClients` here again? Wouldn't it be sufficient to show the AuthClients once on Login?

Would be great when you can find some time to test this. Thanks!

**Comment by marc-farre** [comment]
Thanks, that's awesome!

> Do we need to show the `AuthClients` here again? Wouldn't it be sufficient to show the AuthClients once on Login?

Yes, it's sufficient and perfect doing it this way.

I've removed the OR horizontal bar in commit https://github.com/humhub/humhub/pull/6788/commits/060d112e493a559dd640b3b17714e4e1c7b26c46

image

Now we need to make that work for email and link invites:

`/user/registration/by-link?token=xxxxxxxxx`:
image

`/user/registration?token=xxxxxxxxx`:
image

Problem: the controller is not `AuthController`. So maybe we should move `$showLoginForm` and `$showRegistrationForm` to the User `Module` class?

**Comment by marc-farre** [comment]
@luke- Thanks for you PR.
I've added this commit: https://github.com/humhub/humhub/pull/6788/commits/1b3fabd8788376fc63655299bdbebe032d281071
It allows hiding the form for email invites too.
I've also added the `showOrDivider` attribute to the `AuthChoice` widget allowing to show the OR divider only when we have both the SSO button and the regular login form.
I think this PR is fine now.
Thanks for you work on it!

**Pull request merged**
