### PR TITLE
Fix humhub test case would fail on skipped tests

### PR DESCRIPTION
**Pull request by martin-rueegg**
When a test is annotated with `@skip` (e.g. [`testCreatePublicContentOnPrivateSpace`](https://github.com/humhub/humhub/blob/e7c61781786a6184508681984f4f6e47bac99d9c/protected/humhub/modules/content/tests/codeception/unit/models/ContentVisibilityTest.php#L114) without adding a reason, or [`testConvertTableWithoutBodyAtEnd`](https://github.com/humhub/humhub/blob/e7c61781786a6184508681984f4f6e47bac99d9c/protected/humhub/modules/content/tests/codeception/unit/widgets/RichTextHtmlConverterTest.php#L629)) the Application is not started (`Yii::$app` will be empty), yet the test itself is not skipped (the `@skip` annotation is a [feature of Codeception](url), but [not of PhpUnit](https://github.com/sebastianbergmann/phpunit/issues/3220)).

Hence, tests which are intended to be skipped can (and most likely will) cause the test to [fail](https://github.com/humhub/humhub/actions/runs/5872676823/job/15924640805?pr=6430#step:18:1456).

This PR checks for the `@skip` annotation when a test fails and the application has not been instantiated. In that case, it will throw a propper `SkippedTestError`.

### What kind of change does this PR introduce?

- Bugfix

### Does this PR introduce a breaking change?

- No

### The PR fulfills these requirements:

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] [All tests are passing](#issuecomment-new)
- [x] New/updated tests are included
- [x] Changelog was modified

### CODE REVIEW

**Comment by martin-rueegg** [comment]
Number of skipped tests remained the same with this patch:
- 5 before: https://github.com/humhub/humhub/actions/runs/5859928331/job/15886940747#step:18:1432
- 5 after: https://github.com/humhub/humhub/actions/runs/5878465145/job/15940607104#step:18:1432

**Comment by martin-rueegg** [comment]
I know, this should probably be fixed upstream, but I do not have the resources to go into this.

Also, I do not know why this only hit us while running tests in #6430 and not already.

**Comment by martin-rueegg** [comment]
@luke-  Could I maybe draw your attention to this one, too?

The main magic is happening here: it is checking if the `Yii::$app` is empty (which happens when a test is tagged with a `@skip` annotation), then looks for that annotation and returns it's text in the `SkippedTestError`.

https://github.com/humhub/humhub/blob/6e2be1175fd851f9c16871eb7c0cc59e4169b617/protected/humhub/tests/codeception/_support/HumHubDbTestCase.php#L60-L70

The rest of the code change is a merger of common code of `HumHubDbTestCase.php` and `HumHubHelper.php` with the addition of some debugging note and making sure the main cache is also deleted.

**Comment by martin-rueegg** [comment]
Ah, and calling `parent::setUp();` at the end, rather than the beginning of `HumHubDbTestCase::setUp();` helps avoiding some error with the mails, which is otherwise not correctly instantiated, given that the `Yii::$app` might be empty and the settings are still the one from the previous test ....

**Comment by luke-** [comment]
@martin-rueegg I didn't look at it 100% in detail, but looks good for me, thanks!
Can we also merge this into v.16 `next`?

**Pull request merged**
