### PR TITLE
#143 Remove views/custom directory to @webroot/php-pages. Set new pat…

### PR DESCRIPTION
**Pull request by MasterHans**
…hs in SettingsForm.php.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Move directory custom_pages/views/custom to root as  **php-pages** directory to keep custom PHP files and preserve them from deleting during **custom_pages** module update.
This pull request connected with
https://github.com/humhub/humhub-modules-custom-pages/pull/149

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
We do not allow module specific content (folders) in the core repository.  

As an exception, you may be able to include the "php-pages" folder in GitIgnore, but please add a comment stating that it is part of the Custom Pages module. https://github.com/humhub/humhub/blob/master/.gitignore

**Comment by buddh4** [comment]
I'd not even add this to .gitignore. Why not add a general `module_data` directory or something where modules could manage files?

**Comment by luke-** [comment]
@buddh4 I would like to wait with something like that. ()We need a concept here.) Especially concerning multi node/containerization installations we have to keep an eye on which directories contain what kind of data (e.g. application/user data /application / web accessible).

**Comment by MasterHans** [comment]
> I would like to wait with something like that.

@luke-  I am sorry, could you please point to me where should I put **php-pages** directory and subdirectories:

 php-pages/container_pages/
 php-pages/container_snippets/
 php-pages/global_pages/
 php-pages/global_snippets/

Did not catch that...

**Comment by luke-** [comment]
@MasterHans No problem, let details clarify here: https://github.com/humhub/humhub-modules-custom-pages/pull/149

**Pull request closed without merging**
