### PR TITLE
Enh: Test server output

### PR DESCRIPTION
**Pull request by martin-rueegg**
**What kind of change does this PR introduce?**

- Feature

**Does this PR introduce a breaking change?** (check one)

- No

**The PR fulfills these requirements:**

- It's submitted to the `develop` branch
- [x] All tests are passing
- No new/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:

While running tests, particularly acceptance tests (Cest) it is not clear which URL's have actually been called, as the PHP internal web server does not reveal that information.

This patch is printing that information to the console output.

**Other information:**

### CODE REVIEW

**Comment by martin-rueegg** [comment]
Happy to add a line to the changelog

**Comment by luke-** [comment]
@martin-rueegg Cool feature.

What do you think about adding a color for application/php requests?

e.g.
image


```
    file_put_contents("php://stdout", sprintf("[%s] \e[34m%s:%d [%03d]: %s %s\033[0m\n", date('D M d H:i:s Y'), $_SERVER['REMOTE_ADDR'], $_SERVER['REMOTE_PORT'], indexTextResponseCode::$response->getStatusCode(), $_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']));

```

**Comment by martin-rueegg** [comment]
> @martin-rueegg Cool feature.
> 
> What do you think about adding a color for application/php requests?

If you could give me also the code for red, I could mark red all the requests that do 
- not return a 2xx status, or
- return a 4xx/5xx status, or
- return a 5xx status

**Comment by martin-rueegg** [comment]
or:
- 4xx: orange
- 5xx: red

**Comment by martin-rueegg** [comment]
Done.

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
