### PR TITLE
Fix small gap on TopNav mouse hover

### PR DESCRIPTION
**Pull request by acs-ferreira**
Before:

After:

### CODE REVIEW

**Comment by buddh4** [comment]
The removal of min-height destroys the space chooser dropdown in my test. The gap problem only occures after zooming the page am I right?.

**Comment by acs-ferreira** [comment]
No, you don't need to zoom the page.


What you mean by "space chooser dropdown"?

**Comment by buddh4** [comment]
The following happens on firefox (on chrome it seems to be ok):

topbarpr

**Comment by acs-ferreira** [comment]
Ah ok, i see, you're right.
Can you test latest commit?

**Comment by acs-ferreira** [comment]
Ok, let me do some tests on my side and i'll be back.

**Comment by acs-ferreira** [comment]
Things should be OK now, can you test on your side please?
Tested here against Firefox, Chrome and IE Edge.

**Comment by buddh4** [comment]
thanks!

**Pull request merged**
