### PR TITLE
Improvements in dotenv parsing

### PR DESCRIPTION
**Pull request by gevorgmansuryan**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@gevorgmansuryan Thanks!

How are empty settings handled now?
e.g. `HUMHUB_CONFIG.PARAMS.MODULE_AUTOLOAD_PATHS=` 

Is this simply skipped? In a previous version, an empty value would simply be set here.

Here is a draft for an example file: https://github.com/humhub/humhub-internal/issues/362

**Comment by gevorgmansuryan** [comment]
@luke- yes, .env sends null for empty configs like this `HUMHUB_CONFIG.PARAMS.MODULE_AUTOLOAD_PATHS=`, and it will overwrite current setting with null, it's better to skip them, we can use empty string, false if needed.

**Comment by luke-** [comment]
@gevorgmansuryan Ok, let's skip them.
Let me know when it's implemented. Then I'll merge it.

**Comment by gevorgmansuryan** [comment]
@luke- it's ready to merge

**Review by luke- — APPROVED** [review]

**Pull request merged**
