### PR TITLE
fix declaration with Queue::run($job)

### PR DESCRIPTION
**Pull request by githubjeka**
See https://github.com/humhub/humhub/commit/ac3ef620565f3c5592d6ae75103e74aac00052d4#commitcomment-21615930

### CODE REVIEW

**Comment by luke-** [comment]
Thanks!

**Comment by githubjeka** [comment]
> ArgumentCountError

Too few arguments to function humhub\components\queue\driver\Sync::run(), 0 passed in \humhub\protected\humhub\components\queue\driver\Sync.php on line 49 and exactly 1 expected

**Comment by luke-** [comment]
I think we need to revert your PR.

The problem seems to be that you didn't updated your composer packages.

**Comment by luke-** [comment]
The classes in the yii2-queue component has changed...

**Comment by githubjeka** [comment]
No, this PR fixed PHP 7,1 bug for this code.

**Comment by githubjeka** [comment]
Oh yea, revert please. Sorry for the troubles.

**Comment by luke-** [comment]
Done, no problem!

**Pull request merged**
