### PR TITLE
Enh: Trending Topics

### PR DESCRIPTION
**Pull request by ArchBlood**
As seen in the community site: [here](https://community.humhub.com/s/general-discussion/post/post/view?id=16077)
Screenshot_1

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [x] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
Wouldn't that be better than small modules? This could also be useful in some Spaces.

**Comment by ArchBlood** [comment]
> Wouldn't that be better than small modules? This could also be useful in some Spaces. 

I thought of doing that, but thought it would have been better being a part of the core for ease of extending from other modules.

**Comment by ArchBlood** [comment]
> Hmm, in which cases does it make sense to extend this?

- Topic logic that implements variants to Topics;

In some cases where Topics are actually used, requests for Topic variants are also requested, such as Hashtags, this being a part of the core would mean that this could be extended from the Topic variant instead of having to have multiple modules installed, case in point would be the blog module in humhub-contrib, this module requires both the blog module and the custom pages module to be installed to be used.

I can still create this in a module if the HumHub team thinks that would be a better option, however I can't say much about making it extendable for other modules to use. :thinking:

**Comment by ArchBlood** [comment]
@luke- as of your advice I've created the module, currently I can't release it on the marketplace due to PHP restrictions being PHP 8+ for the module and knowing some people are still using PHP 7.4;

So I'll close this P/R in favor of moving it into a module.

https://github.com/GreenMeteor/trending

**Comment by ArchBlood** [comment]
> @ArchBlood Ok great, maybe a more speaking module id would be fine: e.g. `trending-topics`
I did have that thought at first, but also wanted to keep the module id simple and not with a `-` if possible, I had also thought of using `trendingTopic` but decided against this option.

The overall goal now is the trending part of the module, not necessarily the Topics part, I was thinking of making it so that it could be extended in ways that not only Topics were displayed but the option could be configurable trends. 🤔

**Comment by ArchBlood** [comment]
Another thought, what would HumHub's stance be on changing the icon of the Topics module to `fa-hashtag` instead of `fa-star`?
Screenshot_1

This would work as a better alternative for the growing request for #3936

**Pull request closed without merging**
