### PR TITLE
[v1.17] Remove uisetting include captcha in registration new updated

### PR DESCRIPTION
**Pull request by ultimocoder**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [x] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ultimocoder** [comment]
Hi @luke- and @marc-farre 

Updated the PR because in last branch lot of unwanted changes has been pushed by mistake.

 Please have a look and let me know your feedback.

**Comment by marc-farre** [comment]
@ultimocoder Thanks for your contribution!
Looks fine. Small suggestions in commit https://github.com/humhub/humhub/pull/7086/commits/73fb5aa66cf4cac2d85341f6778fe64ddcb77d17

**Comment by ultimocoder** [comment]
> @ultimocoder Thanks for your contribution! Looks fine. Small suggestions in commit [73fb5aa](https://github.com/humhub/humhub/commit/73fb5aa66cf4cac2d85341f6778fe64ddcb77d17)

Hi @marc-farre,

Thank you for your feedback and updating the changes.

Please approve the review request so that I can merge the changes.


I don't know why I am getting this CLA error suddenly for this PR, but anyway I think we can proceed with merging.
> **ultimocoder** seems not to be a GitHub user.

**Comment by marc-farre** [comment]
> Please approve the review request so that I can merge the changes.
> 
> I don't know why I am getting this CLA error suddenly for this PR, but anyway I think we can proceed with merging.

I'll leave @luke- approve this PR.

**Comment by ultimocoder** [comment]
> > Please approve the review request so that I can merge the changes.
> > I don't know why I am getting this CLA error suddenly for this PR, but anyway I think we can proceed with merging.
> 
> I'll leave @luke- approve this PR.


Hi @marc-farre, 
Please check below comment on your checking 
https://github.com/humhub/humhub-internal/issues/173#issuecomment-2188141623

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
