### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by samdark**
- Fixed missing method modifiers.
- Fixed case mismatch.
- Fixed calling non-static methods statically.

### CODE REVIEW

**Comment by luke-** [comment]
Great, maybe it's better to push this to the 1.2-dev branch?

**Comment by samdark** [comment]
As far as I know, you can change branch right from GitHub UI.

**Comment by cebe** [comment]
Yes, clicking "Edit" Button on top right of the PR allows changing the base branch.

**Comment by luke-** [comment]
@cebe Ah, yeah :-)

**Pull request merged**
