### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by WASasquatch**
Prevent 500 Non-Writable Errors warn user to pass CHMOD permissions to YIIC resources.

### CODE REVIEW

**Comment by luke-** [comment]
+    - /protected/yiic
+    - /protected/yiic.bat
+    - /protected/yiic.php

Should be writable --> executable....

**Comment by WASasquatch** [comment]
Ugh I purposely had Executable in my head, I swear. I have bad dyslexia. Coders worse nightmare haha. How do you edit pulls without it trying to create another?

**Comment by luke-** [comment]
Thanks, but 4.) Make the following files executable ~~by the webserver~~

**Comment by WASasquatch** [comment]
Edited, though not sure why we'd want it to be executable by a group or user and not only web server?

**Pull request merged**
