### PR TITLE
Hashtag feature

### PR DESCRIPTION
**Pull request by feldrim**
Hashtag feature by @Censtudios (Issue: https://github.com/humhub/humhub/issues/1347)

### CODE REVIEW

**Comment by feldrim** [comment]
Scritinizer shows issues independent from my commit. What is the problem?

**Comment by feldrim** [comment]
I added your contribution but Scrutinizer has displayed some problems.

**Comment by Felli** [comment]
With how it's setup right now it calls for the word YOURHASHTAG over what it should be calling which is #YOURHASHTAG and when trying to implement the use of #YOURHASHTAG it just turns into a redirect link to the search. :disappointed:

_Tested in 1.0.0-beta.2 & 1.0.0-beta.4_

**Comment by buddha87** [comment]
Hi, will close this, I'am sure such a feature will be included in the future but can't tell you when. Thanks for your effort.

**Pull request closed without merging**
