### PR TITLE
Fix saving of OEmbed provider endpoint URL

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5716

### CODE REVIEW

**Review by ArchBlood — APPROVED** [review]
Looks good for me so far, although I'm not sure why I'm still getting the following error?

Screenshot_1

**Comment by yurabakhtin** [comment]
@ArchBlood It seems issue from your php editor, because I don't see this in PhpStorm from my side:

phpstorm

You can try to delete the end of line and create it again, probably there is some hidden char in the end of line.

**Comment by ArchBlood** [comment]
> @ArchBlood It seems issue from your php editor, because I don't see this in PhpStorm from my side:
> 
> phpstorm
> 
> You can try to delete the end of line and create it again, probably there is some hidden char in the end of line.

My issue seems to be any entry of `$query[]` and any variation of the array and variable combo, of course, the PHP editor is set to PHP 7.4 and nothing else. :thinking:

**Comment by yurabakhtin** [comment]
@ArchBlood Yes, strange, just try to remove the line and one below completely and retype them both char by char manually, because your editor finds a char `$end-of-file` somewhere there, it is hidden for our eyes, otherwise I don't have any idea more.

**Comment by ArchBlood** [comment]
> @ArchBlood Hmm, for me there is also no error in the IDE.

I'm now understanding why this is the case after reading more into some of the explanations found here;

https://stackoverflow.com/questions/47540423/how-does-isset-not-throw-an-error-when-evaluating-array-properties

So simply put we're using a non-existing variable or something like this, which is probably why most IDE don't read this but built-in server editors do? I'm not completely sure myself.

https://stackoverflow.com/questions/1960509/how-to-avoid-isset-and-empty

After testing with Atom.io I also don't see any errors but still leaves me with questions that I have yet to find any answers to. 🤔

Screenshot_2

**Pull request merged**
