### PR TITLE
Guess timezone for new accounts #4272

### PR DESCRIPTION
**Pull request by sahartak2025**

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
Great work, thanks!

**Review by luke- — APPROVED** [review]

**Comment by buddh4** [comment]
If the returned timeZone is somehow not part of [https://www.php.net/manual/en/datetimezone.listidentifiers.php](DateTimeZone::listIdentifiers) the validation and registration would fail?

**Comment by buddh4** [comment]
Also available timezones are restricted in https://github.com/humhub/humhub/blob/7cf1349174656493097a8835d28701ffb40c3448/protected/humhub/libs/TimezoneHelper.php not sure if this PR would allow legacy timezones (not that a browser would use one but should be validated)

**Comment by luke-** [comment]
Good point, as a fallback we should simply not set the time zone as before.

@sahartak2025 Can you create such "Validate or Null Rule"?

**Comment by buddh4** [comment]
The validation rule is configured in https://github.com/sahartak2025/humhub/blob/6518fdd4db343e02e907f622249d978cfb27d46b/protected/humhub/modules/user/models/User.php#L148 maybe replace this validation rule with a custom validation function which resets the value if not null.

**Pull request merged**
