### PR TITLE
Fix doc for Helpers::SqlMode

### PR DESCRIPTION
**Pull request by githubjeka**
Rel #2693

### CODE REVIEW

**Comment by luke-** [comment]
Please apologize the so delayed reply.
Is this PR and #2693 still a problem? I could not reproduce it, maybe it was fixed somehow else in the meantime.

**Comment by githubjeka** [comment]
Hmm... On local, in one place it works, but in another place, this code doesn't work.
It's local problem probably

**Comment by githubjeka** [comment]
Again... 
I catch it when clear cache and module uninstall & install...

**Comment by githubjeka** [comment]
Yii2 issue https://github.com/yiisoft/yii2/issues/1988

**Pull request closed without merging**
