### PR TITLE
Fix #6209: Timeout on php yii queue/run executed by command line

### LINKED ISSUE #6209: Timeout on php yii queue/run executed by command line
### What steps will reproduce the problem?

I cannot reproduce. It's the first time it happens.
The error occurred on cron run.
Command executed: `php yii queue/run`

### What is the expected result?

No bug

### What do you get instead?

A timeout error.
As it was executed by command line, there should be no timeout.
But when analyzing the error log bellow it seems to be a timeout check in the code: `Symfony\Component\Process\Process->checkTimeout()`.

```
2023-03-28 17:38:02 [-][-][-][error][queue] Could not execute queued
job! Message: The process "'/usr/bin/php7.4'
'/var/www/humhub/protected/yii'
'queue/exec' '39646' '300' '1' '20305' '--color='" exceeded the
timeout of 300 seconds. Trace:#0
/var/www/humhub/protected/vendor/symfony/process/Process.php(430):
Symfony\Component\Process\Process->checkTimeout()
#1
/var/www/humhub/protected/vendor/symfony/process/Process.php(254):
Symfony\Component\Process\Process->wait()
#2
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(193):
Symfony\Component\Process\Process->run()
#3
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126):
yii\queue\cli\Command->handleMessage()
#4 [internal function]:
yii\queue\cli\Command->yii\queue\cli\{closure}()
#5
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144):
call_user_func()
#6
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83):
yii\queue\cli\Queue->handleMessage()
#7 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#8
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117):
call_user_func()
#9
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93):
yii\queue\cli\Queue->runWorker()
#10
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56):
yii\queue\db\Queue->run()
#11 [internal function]: yii\queue\db\Command->actionRun()
#12
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array()
#13
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178):
yii\base\InlineAction->runWithParams()
#14
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180):
yii\base\Controller->runAction()
#15
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552):
yii\console\Controller->runAction()
#16
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180):
yii\base\Module->runAction()
#17
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147):
yii\console\Application->runAction()
#18
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384):
yii\console\Application->handleRequest()
#19
/var/www/humhub/protected/yii(29):
yii\base\Application->run()
#20 {main}
in
/var/www/humhub/protected/humhub/modules/queue/Events.php:48
2023-03-28 17:33:01 [-][-][-][info][application] $_GET = []
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 7.4
| Operating system | Ubuntu 20.04

### PR DESCRIPTION
**Pull request by gevorgmansuryan**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@gevorgmansuryan Thanks!

In principle, we should still have a timeout, but there are some jobs that need longer time (e.g. `SearchIndexRebuild`, `SendActivitySummaries`) and some that should run rather fast.

As example, for Search Rebuilds we tried to fix this here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/search/jobs/RebuildIndex.php#L49 I'm not sure if it's still working correctly. We should find another solution for these cases.

Can you please check our options here?

**Comment by luke-** [comment]
@gevorgmansuryan Ah ok, got it.

It would still be good if we could somehow distinguish between:

- Rather short running jobs (e.g. update document in search index, send notification) - This should be the default. Here 300sec is certainly enough.

- Long running jobs (e.g. rebuild complete search index, send mail summaries) Here a much higher timeout would be useful.

Can you please check what possibilities we have here?

**Comment by gevorgmansuryan** [comment]
@luke- sure, i will

**Comment by gevorgmansuryan** [comment]
@luke- we can make default 5 minutes instead of 30 secs , for Long running jobs there is already exist getTtr

**Comment by luke-** [comment]
@gevorgmansuryan The default Ttr seems to be  already 5 minutes. https://github.com/yiisoft/yii2-queue/blob/master/src/Queue.php#L75

So It would be good if we could have a standardized and configurableway to create long-running jobs with a default Ttr of e.g. 1 hours. For very large installations, this limit can then be increased even further.

**Pull request closed without merging**
