### PR TITLE
Html 5 player for the attached videos #1707

### PR DESCRIPTION
**Pull request by Daha62**
Fixed issue #1707

### CODE REVIEW

**Comment by cagatayldzz** [comment]
...video src="<?= $file->getUrl(); ?>" class="video-cs" controls></video...


Css
video.video-cs{max-width: 100%;outline: 0;}

**Comment by Daha62** [comment]
@cagatayldzz , fixed )

**Comment by luke-** [comment]
Great!

What happens if the browser doesn't support the playback of the video file format?
E.g. webm and Internet Explorer...

@Daha62 Can you please accept our CLA at https://humhub.org/cla/github/sign

**Comment by cagatayldzz** [comment]
IE - 8 
mp4 smoothly
ekran alintisi

**Comment by luke-** [comment]
What happens with video files, when the browser doesn't support the format?

**Pull request closed without merging**
