### PR TITLE
Enh New translations for French

### PR DESCRIPTION
**Pull request by nminelle**

### CODE REVIEW

**Comment by cagatayldzz** [comment]
http://translate.humhub.org

**Comment by nminelle** [comment]
Asked for membership for the French Space like years ago. Like few other guys.
No one never got an answer... It looks that all past French translations have been committed through github, so I try to share that way too. Is it a problem (well sorry for other languages followers)?

**Comment by buddha87** [comment]
@nminelle just tell me your name, the problem is there were too many requests for the french space, and it's too insecure just to allow all of them.

**Comment by nminelle** [comment]
http://translate.humhub.org/index.php?r=user%2Fprofile&uguid=c4e9e99d-68fa-4bc2-88c6-ac5b24b60201

**Comment by buddha87** [comment]
@nminelle  I've accepted your request. Thanks for your effort

**Comment by nminelle** [comment]
Thanks. Already made few contribs, I'll continue in the next few days.

**Pull request closed without merging**
