### PR TITLE
Fix: Improve migration error messages

### PR DESCRIPTION
**Pull request by martin-rueegg**
### What kind of change does this PR introduce?

- Bugfix

### Does this PR introduce a breaking change?

- No

If yes, please describe the impact and migration path for existing applications:

### The PR fulfills these requirements

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [x] All tests [tests](#issuecomment-new) are passing
- [x] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### Related
- https://github.com/humhub/rest/issues/148#issuecomment-1866279261
- https://github.com/humhub/humhub/pull/6550

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@martin-rueegg Thanks. Any idea why the tests are failing?

**Comment by martin-rueegg** [comment]
> @martin-rueegg Thanks. Any idea why the tests are failing?

It is just one test: installing a module with migration. I need to look into it. Not sure I manage today though.

**Comment by luke-** [comment]
> > @martin-rueegg Thanks. Any idea why the tests are failing?
> 
> It is just one test: installing a module with migration. I need to look into it. Not sure I manage today though.

Thank you, absolutely no hurry.

**Review by luke- — APPROVED** [review]

**Comment by martin-rueegg** [comment]
@luke- I tried to merge `develop`, rather than to rebase. But still, Auto-merge has been disabled ...

**Comment by luke-** [comment]
> @luke- I tried to merge `develop`, rather than to rebase. But still, Auto-merge has been disabled ...

Now it's working. Thank you!

**Pull request merged**
