### PR TITLE
Add “codeception/module-rest” for test REST API modules

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Other information:**
Related to issue https://github.com/humhub/humhub-modules-rest/issues/33 in order to test REST API endpoints.

### CODE REVIEW

**Review by luke- — APPROVED** [review]
Looks good.  Should also be unproblematic to merge it directly into the master.

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Any idea regarding the tests on this PR?

**Comment by yurabakhtin** [comment]
@luke- 

> Any idea regarding the tests on this PR?

This PR was created only in order to make work API tests on modules like https://github.com/humhub/humhub-modules-mail/pull/217, I don't see what code from this PR #4960 can be tested.

**Comment by luke-** [comment]
@yurabakhtin Seems somehow the `composer.lock` in this PR breaks the Tests.
https://github.com/humhub/humhub/pull/4960/checks?check_run_id=2114257056#step:9:10

I'll take a look at it later.

**Comment by luke-** [comment]
@yurabakhtin The tests are now running successfully. Should I merge it into the master or wait?

**Comment by yurabakhtin** [comment]
@luke- Yes it may be merged if we want to make works the new changes from PRs https://github.com/humhub/humhub-modules-mail/pull/217 and https://github.com/humhub/humhub-modules-rest/pull/55

**Comment by luke-** [comment]
@yurabakhtin Ok is merged.

**Pull request merged**
