### PR TITLE
Added: NGINX Documentations

### PR DESCRIPTION
**Pull request by Felli**
See #3343

### CODE REVIEW

**Comment by danielkesselberg** [comment]
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by Felli** [comment]
@danielkesselberg sadly the `if` clause seems a necessary evil in some cases, although using `try_files` instead haven't given me any results back, could you do some test for this?.

**Comment by acs-ferreira** [comment]
It also lacks (at least) the protected folders (actually by `.htaccess` files)

**Comment by luke-** [comment]
FYI: 

We will soon change the documentation to another system/repo. 
Then we will reorganize the documentation and also add details like NGINX like this.

**Comment by luke-** [comment]
https://docs.humhub.org/docs/admin/server-setup#nginx

**Pull request closed without merging**
