### PR TITLE
Use RichTextField for user approval messages

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5229

### CODE REVIEW

**Comment by ArchBlood** [comment]
Seeing as `protected/humhub/modules/admin/views/approval/approve.php` was updated, so should the `decline.php` file, shouldn't it?

**Comment by ArchBlood** [comment]
Also... Not sure why but when the mail is sent out it gives an incorrect registration token? Might be unrelated but something that should be looked at 🤔

Screenshot_2
Screenshot_3
Screenshot_4

**Review by luke- — APPROVED** [review]

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Can you please check the `decline.php` view and the tests?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please check the `decline.php` view

Commit https://github.com/humhub/humhub/pull/5234/commits/8c4999897d4224a5e2d5735ffeb0302dab596ac4

> and the tests?

Commit https://github.com/humhub/humhub/pull/5234/commits/78078683cf96c52eb4f2e60b40b43d1a1e3e87ae: I have changed the translatable strings only for `de` locale, should I change the same strings for all locales as well?

@ArchBlood 

> Also... Not sure why but when the mail is sent out it gives an incorrect registration token? Might be unrelated but something that should be looked at 🤔

It is not related to this issue, but I tested and for me it works:

reg_token

It seems like the record with requested token was not created in the DB by some reason or the record was deleted.

**Comment by ArchBlood** [comment]
> @ArchBlood 
> 
> > Also... Not sure why but when the mail is sent out it gives an incorrect registration token? Might be unrelated but something that should be looked at 🤔
> 
> It is not related to this issue, but I tested and for me it works:
> 
> reg_token
> 
> It seems like the record with requested token was not created in the DB by some reason or the record was deleted.

For me personally, a `3D` is applied at the beginning of all tokens, still trying to figure it out but only happened as soon as I applied the changes, I'll check things out on my end 🤔

**Comment by yurabakhtin** [comment]
@ArchBlood Thank you for the info about `3D`, because from your first report I thought the problem in the different token completely. Yes, the email message source contains `=3D`, I think because `Content-Transfer-Encoding: quoted-printable`, but it seems your email client doesn't decode it correctly to normal view:

investigate_3D_in_email

**Comment by luke-** [comment]
@yurabakhtin @ArchBlood Thanks, looks fine for me!

@yurabakhtin Regarding the test strings: I'm going to merge it and rebuild the translation messages on our translation server.

**Review by luke- — APPROVED** [review]

**Comment by ArchBlood** [comment]
> @ArchBlood Thank you for the info about `3D`, because from your first report I thought the problem in the different token completely. Yes, the email message source contains `=3D`, I think because `Content-Transfer-Encoding: quoted-printable`, but it seems your email client doesn't decode it correctly to normal view:
> 
> investigate_3D_in_email

Seems that I found my specific issue was due to PHP 8.0.9, works fine in PHP 7.4.22 🤔
Anyways thanks @yurabakhtin for your extra work

**Pull request merged**
