### PR TITLE
Use settings->baseUrl for invitation links. Fix #1316

### LINKED ISSUE #1316: Wrong URL in users invite
Hello,

I just can't fix the URL which is in the user invites. Humhub is installed on my NAS and email invite keep sending a sign up link with a local IP in the URL... Found no entrey in database as humhum can be reach via à subdomain on my NAS...

### PR DESCRIPTION
**Pull request by marcodisarno**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
Thanks for your contribution.

Do you use HumHub under multiple URLs or how does the problem occur?

Maybe we should simply move the task of sending the invitation URL to an ActiveJob in the queue, then the BaseURL is automatically used.

**Comment by marcodisarno** [comment]
Hey!

> Do you use HumHub under multiple URLs or how does the problem occur?
I'm using it in a docker (inspired by https://github.com/mriedmann/humhub-docker) that I then deploy automatically to different hosts, set by `php yii installer/set-base-url <HOST>`. The containers then are proxy-passed to by a front-door nginx.

Note: in my particular case I could also just add configurations for the target hosts and switch those during deploy:

```
'urlManager' => [
    'hostInfo' => 'http://example.com/',
    // ...
]
```

But it would feel like double-configuring the same thing. And this open issue #1316 convinced me this needs something a little more general.

> Maybe we should simply move the task of sending the invitation URL to an ActiveJob in the queue, then the BaseURL is automatically used.

I'm not very familiar with Yii so I don't know how this solves the problem, but I trust you do. Plus, I think it is a very good idea to have these invitations in a queue. Especially since you can enter comma-seperated emails in the Form, which (haven't checked) might not be restricted.

**Comment by marcodisarno** [comment]
Hi again, it happens to other Email notifications as well, e.g. have I just tried to change the top admin (id=1) e-mail address, which summons a confirmation mail to the new address.

So we need something really "general" here.

**Comment by luke-** [comment]
Did you configured the FrontEnd proxy in the config:
https://docs.humhub.org/docs/admin/reverse-proxy#trusted-hosts

You can also use the word `any` instead of IP for testing.

**Pull request closed without merging**
