### PR TITLE
 The participants modal box replaces the content sub-menu icon with a…

### PR DESCRIPTION
**Pull request by gevorgmansuryan**
https://github.com/humhub/calendar/issues/419

### CODE REVIEW

**Comment by luke-** [comment]
@gevorgmansuryan Thanks!
@yurabakhtin Can you please review?

**Comment by yurabakhtin** [comment]
@luke- @gevorgmansuryan I have tested the issue as described here https://github.com/humhub/calendar/issues/419 and this core PR https://github.com/humhub/humhub/pull/6565 together with calendar PR https://github.com/humhub/calendar/pull/421 don't solve it on my side, I still see the loader on the menu icon place when I press on "1 Attending".

I find the links like `1 Attending` call the action `calendar.editModal` - https://github.com/humhub/calendar/blob/master/resources/js/humhub.calendar.js#L306, I think we just need to remove 2 first lines of the function:

```js
var streamEntry = Widget.closest(evt.$trigger);
streamEntry.loader();
```

because I don't find a reason to lock the menu with loader when we open the edit modal window.

I guess the lines were added there by mistake in this very old commit https://github.com/humhub/calendar/commit/27e2cd8a6bc0a91fbd4852510969ae8b5270234c#diff-e252b57a319529c2bd280b5e31682db169f2e01b84ab90116bcfe76d2fed769eR361-R362, probably it was copied from the `deleteEvent` where we need it.

**Comment by gevorgmansuryan** [comment]
@yurabakhtin interesting. It works correctly for me. Did you cleared files from assets folder from main repo before testing, because `'forceCopy' => true` is not always working correctly.

**Comment by gevorgmansuryan** [comment]
var streamEntry = Widget.closest(evt.$trigger);
streamEntry.loader();

I've reverted my changes and deleted these lines, the loader still visible (

**Comment by yurabakhtin** [comment]
> It works correctly for me. Did you cleared files from assets folder from main repo before testing, because `'forceCopy' => true` is not always working correctly.

@gevorgmansuryan Yes, I clear my assets folder before test new changes in js and css files, also I refresh browser with Ctrl+Shift+R and also I find your new changes in the loaded js files but it didn't work and I have described why we need to do changes in the function `calendar.editModal`, so it is strange to why the deleting of these lines didn't help you, may you forgot to run `grunt build`, are you sure the new updated file is loaded on you browser properly?

wiht-lines

without-lines

**Comment by gevorgmansuryan** [comment]
@yurabakhtin ah ok, got it, sorry ))) I've checked `attend`, `maybe`, `decline` buttons and my fix is for these. Your suggestion helped for `1 Attending`. Thanks for help!

**Comment by yurabakhtin** [comment]
> I've checked `attend`, `maybe`, `decline` buttons and my fix is for these.

@gevorgmansuryan I have tested these buttons without your fix and don't find any problem there.
I see only single issue with with the loader when we click on the links like `1 Attending` because they call the function `editModal`.

https://github.com/humhub/humhub/assets/6995524/3f13f84d-b32f-442d-b2af-e33c63c78ed7

I.e. I cannot understand why we need to merge this core PR https://github.com/humhub/humhub/pull/6565 and the calendar PR https://github.com/humhub/calendar/pull/421.
Could you please show what the PRs fix? Thanks.

---
If I have understood the issue https://github.com/humhub/calendar/issues/419 correctly, we need either create new PR where we delete the 2 lines from the function `editModal` as I described above or modify your calendar PR https://github.com/humhub/calendar/pull/421, and close this core PR.

**Comment by yurabakhtin** [comment]
@gevorgmansuryan I have meant we need only the changes from PR https://github.com/humhub/calendar/pull/426, please read https://github.com/humhub/calendar/issues/419#issuecomment-1736972215.

**Pull request closed without merging**
