### PR TITLE
Shorten high member numbers

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Issue: https://github.com/humhub/humhub/issues/4754

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Thank you! Can you add a few more unit tests here? Also, Thousand, Million & Billion will do. Further levels should not be necessary. (This only creates unnecessary translation work).

**Comment by yurabakhtin** [comment]
@luke- 

> Can you add a few more unit tests here? Also, Thousand, Million & Billion will do. Further levels should not be necessary. (This only creates unnecessary translation work).

Do you still need this? If yes, then it is strange why you closed the issue https://github.com/humhub/humhub/issues/4754 and moved to the "Done" list, because I am working on another task currently so I will not find this task in future and it will be missed by me.

**Comment by luke-** [comment]
@yurabakhtin Ok sorry, yes it's still open.  For me it is sometimes a bit confusing when I have a task twice in my GitHub notifications (Issue & PR) - that's why I closed the Issue.

**Comment by yurabakhtin** [comment]
@luke- 

> Also, Thousand, Million & Billion will do. Further levels should not be necessary. (This only creates unnecessary translation work).

Ok, I removed the code of "Trillion" and "Quadrillion" here https://github.com/humhub/humhub/pull/4771/commits/d054e499c59dd173953a3173410ef35c1d12de78#diff-e2b618d96a28158cdfdddc019a6c3531663be549bba96faff27f42946d13840aL103-L108

> Can you add a few more unit tests here?

Please check my tests here https://github.com/humhub/humhub/pull/4771/commits/d054e499c59dd173953a3173410ef35c1d12de78#diff-9afb473cda19dc41377c0455ebfc57fb907d09f16c67fbda40e910138a677d39R18-R34, review especially:

- `999999500 => '1000M',`
- `999999999500000 => '1000000B',`

This happens because yii core function `Formatter->formatNumber()` works this way.
Maybe the second is ok but in first case we should display either `999M` or `1B`, please confirm I should find a solution and what way you prefer.

**Comment by luke-** [comment]
@yurabakhtin I think we can keep it that way. The problem only affects very large numbers, doesn't it? I've added a few more tests and I guess that's ok!

**Comment by yurabakhtin** [comment]
@luke- 

> The problem only affects very large numbers, doesn't it?

Yes, as I wrote only single case has the problem for numbers between `999999500` and `999999999`.

> I've added a few more tests and I guess that's ok!

Your new tests work well, I tested and result is: `OK (1 test, 20 assertions)`

**Review by luke- — APPROVED** [review]
@yurabakhtin Thanks!

**Pull request merged**
