### PR TITLE
New interface TabbedForm for activate first tab with error input

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/tasks/pull/172#issuecomment-976209863

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin 
Doesn't it make more sense to maybe create a TabsForm class in this package `humhub\modules\ui\form\widgets`?
Maybe TabsForm can extend from Tabs?

**Comment by yurabakhtin** [comment]
@luke- 

> Doesn't it make more sense to maybe create a TabsForm class in this package `humhub\modules\ui\form\widgets`? Maybe TabsForm can extend from Tabs?

Currently the class `humhub\modules\tasks\models\forms\TaskForm` is extended from `yii\base\Model`,
but the class `humhub\widgets\Tabs` is extended from `yii\bootstrap\Tabs`.
Do I understand you correctly that you want to create a new class extended from `humhub\widgets\Tabs` and `yii\base\Model`? If yes, then it is impossible, because only one class can be used for extending, it is why I decided to use the interface.
If I didn't understand you please give me an example what you mean, thanks.

**Comment by luke-** [comment]
@yurabakhtin I meant following naming:

- `humhub\modules\ui\form\interfaces\TabbedFormModel`. (Please add to the description, that this interface is related for `Model` classes only   
- `humhub\modules\ui\form\widgets\TabsForm` (extended from `Tabs`) with `TabbedFormModel` support

**Comment by yurabakhtin** [comment]
@luke- Ok, new changes in the core commit https://github.com/humhub/humhub/pull/5472/commits/3d2616a4b7d4e69f311ba770f9ad4fb33564c5d1.
Task module commit https://github.com/humhub/tasks/pull/175/commits/30b8f4b9ba6b4ac14694cb34606bd1dddd3d24a1.

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Can you please add some tests for this?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please add some tests for this?

Currently new class `FormTabs` and interface `TabbedFormModel` are used only in the module `tasks` here https://github.com/humhub/tasks/pull/175, i.e. we can create tests only in the module only, but the core PR is not merged yet, so tests are broken there with error `Interface 'humhub\modules\ui\form\interfaces\TabbedFormModel' not found`.

**Comment by luke-** [comment]
@yurabakhtin Can we add some "mock" code to the core for such cases?

**Comment by yurabakhtin** [comment]
@luke- 

> Can we add some "mock" code to the core for such cases?

Ok, I created a test in the commit https://github.com/humhub/humhub/pull/5472/commits/cc3d91be1f54faa286513b6168cf423871010867

**Review by luke- — APPROVED** [review]

**Pull request merged**
