### PR TITLE
Use permalink comment in notification

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature
- [x] Refactor

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5457

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by funkycram** [comment]
@yurabakhtin This is a great feature!

The only think is, when there are many comments and the link point to an old comment, you do not see it because you need to clic on "Show all xxx comments", and then the comment is not highlighted anymore.
Example: https://community.humhub.com/comment/perma?id=38409

**Comment by luke-** [comment]
@yurabakhtin I can reproduce this. You may need to become member of the "Hosting" space.
image

There is no indication of the highlighted content. Community is using the latest version

**Comment by yurabakhtin** [comment]
@luke- Yes, I can reproduce this after joining to the space.

I checked links of the other comments from the content and it seems there is some cache issue, which already I fixed in the PR https://github.com/humhub/humhub/pull/5448.
Some links work well with highlighted:

- https://community.humhub.com/s/hosting/?contentId=159094&commentId=23925 - Highlighted
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=24539 - Highlighted
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=28819 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=28965 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=29025 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=33754 - Highlighted
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=34809 - Highlighted
-  https://community.humhub.com/s/hosting/?contentId=159094&commentId=35935 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=36236 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38110 - Highlighted
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38262 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38372 - Highlighted
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38365 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38365 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=38409 - No
- https://community.humhub.com/s/hosting/?contentId=159094&commentId=39342 - No

What if you will try to do "Flush Caches" in advanced administration settings?
However I checked the code and there no caching for case when `commentId > 0`.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5474.

**Comment by funkycram** [comment]
Thanks @yurabakhtin for your quick fix (not tested)!

**Comment by luke-** [comment]
@yurabakhtin Thanks

I've just rolled out the fix on our community site for testing.

**Comment by funkycram** [comment]
Works fine, thanks!

**Pull request merged**
