### PR TITLE
Fix regression with Membership cache

### PR DESCRIPTION
**Pull request by martin-rueegg**
**What kind of change does this PR introduce?** (check at least one)

- Bugfix for regression introduced in [Performance Improvements](https://github.com/humhub/humhub/commit/9fabc0e2d40b580527a57eb32f3a4a29903ca3f2#diff-784788c31ac7b8ee4174e073efbfc818d7791d600260533363a35a5548670685R233-R235)  (#6375)

Requesting space membership does work, but the buttons on the space list are not updated. Therefore, the issue only happens in case the space membership is requested from the spaces list
http://humhub.local/index.php?r=space%2Fspaces

**Does this PR introduce a breaking change?** (check one)

- No

**The PR fulfills these requirements:**

- It's submitted to the `develop` branch
- All tests are passing -> **This regression is not covered by a test**
- [x] New/updated tests are included
  - **to be done:** testing the request to space membership not only from the space page, but also from the spaces list. See `RequestMembershipCest`. => #6477
- [x] Changelog was modified

### CODE REVIEW

**Comment by luke-** [comment]
@gevorgmansuryan Can you please take a look?

**Comment by martin-rueegg** [comment]
One problem here is that most tests run without active cache.

I have now added tests for both the cached as well as the uncached calls. However, I've not set up to use the cache during the test.

**Comment by martin-rueegg** [comment]
The particular situation is in `\humhub\modules\space\behaviors\SpaceModelMembership::addMember`:

In https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/space/behaviors/SpaceModelMembership.php#L427 which is called from here https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/space/controllers/MembershipController.php#L95

... the membership is retrieved (and not found) and hence a `null` value is stored in the cache.

When then later, back in https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/space/controllers/MembershipController.php#L97 or rather in the respective https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/space/controllers/MembershipController.php#L312 yet again in https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/behaviors/SpaceModelMembership.php#L63 the membership is again loaded, it gets the `null` from the cache, rather than the meanwhile created record.

**Comment by martin-rueegg** [comment]
Not quite sure, why the [LegitimationTest::testSpaceMemberCanSeePrivateContent](https://github.com/humhub/humhub/actions/runs/5645932798/job/15292766597?pr=6457) failed now. I can't reproduce the error locally. Here the test succeeds. 

See if clearing the legitimate content container id cache will solve the issue. But then again, this only makes sense, if the cache would be active during the test ...

**Comment by martin-rueegg** [comment]
Ok, another interesting observation:

When I run the entire test suite, the LegitimationTest fails:

    protected/humhub/tests$ php $HUMHUB_VENDOR_BIN/codecept run -v

However, when I only run the tests from the affected module, they succeed:

    protected/humhub/modules/live/tests$ php $HUMHUB_VENDOR_BIN/codecept run -v

Maybe something that should be looked at, too?

**Comment by martin-rueegg** [comment]
Regarding the caching of the Membership, I doubt that there is any performance improvement in it's original implementation. In fact, I believe the following line simply create overhead and increase complexity:

https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/space/behaviors/SpaceModelMembership.php#L232-L236

What this code is basically doing:

1. It checks if the object exists in the array of the local member variable
2. If not, it checks, if it's in the cache (which is an array cache by default, unless it's a console process, then it's simply a dummy cache)
3. If it's not there, it looks up the database and
   1. Saves the Membership/null in the cache (if not dummy)
   2. Saves the Membership/null in the local member variable
4. Returns the Membership/null.

As the local member variable has the same live time as the runtime cache (if it's an array cache) will never be an entry in the cache, unless the space object (and hence the `SpaceModelMembership` behavior is recreated. In which case, the local member variable does not make much sense.

The approach I took was to use a static variable in the Membership class. Which definitively has the same live span as the array cache (unless I'm mistaken). In which case ...

- ... using only the static variable is more performant
- ... using only the cache is more configurable (as the runtime cache can be influenced by the config)

Either way, I'd suggest to only use either an local array _or_ the cache, but not both.

**Comment by martin-rueegg** [comment]
Ok, so the reason why the test failed when running the full suite was that the array did not get cleared during the test setup, while on the other hand the database table got emptied. Hence, the Membership object was still available in the array (so it was not re-created in the db) and hence, when then getting the posts it would not be visible due to the missing Membership.

In my previous message I've laid out, why it doesn't make much sense to have _both_ the array cache _and_ the `runtimeCache` as they are basically doing the same (in this situation), the later just with additional overhead.

Still, for being consistent with the rest of the application _and_ for the benefit of being able to configure/influence the cache behaviour, I've now opted to remove the "local" array, and exclusively use the `runtimeCache` instead.

If, however, @luke- would prefer to use the array here in any case, then we would have to make sure

- the array is initialized empty when loading the class, i.e. in Membership.php
- Since in the test suite the class seem _not_ to be reloaded, it would also have to be cleared wherever the Membership table gets cleared.
- Alternatively, the array must be moved back into an object instance, as it was before, but losing the benefit of using the cache throughout the application.
-

**Comment by luke-** [comment]
@martin-rueegg Thank you for your help here. I also see no reason (except maybe in the Console scenario) to keep both "caches" (`runtimeCache` and static variable). So for me, your solution with the `runtimeCache` is fine. Consistency is a good argument here.

One small point, if possible, I would prefer when the method `Membership::findMembership(Space $space, User $user): ?membership` would have strict types and does not allow `int` argument.  What do you think?

Probably it really makes sense to enable caching during tests? Should we create a new issue for this?

@gevorgmansuryan Can you please also take a look into this? Could there possibly be similar issues in your recent `runtimeCache` implementation?

**Comment by martin-rueegg** [comment]
> One small point, if possible, I would prefer when the method `Membership::findMembership(Space $space, User $user): ?membership` would have strict types and does not allow `int` argument. What do you think?

Thank you for asking for my opinion.

I personally would suggest to create at least two corresponding methods for the User and Space classes (potentially with caching, too):

- `User::findUser($user): ?User`
- `User::findUserAsId($user): ?int`
- `Space::findSpace($space): ?Space`
- `Space::findSpaceAsId($space): ?int`

The `User::findUser` and `Space::findSpace` would do the real work, the other two only get the `$object->id` from the main methods, unless the result is `null`.

The code in
https://github.com/metaworx/humhub/blob/fbc093a9358bb02fe4d8dcdc1309f74396855f85/protected/humhub/modules/space/models/Membership.php#L413-L425
would then be moved into the respective methods.

This would allow to simplify all these countless occurrences of similar code to be reduced to one function call and you know exactly that you either get a User object - or a UserID respectively - or `null`, no matter what you put in (int, User, or null). In case of an invalid data type, an exception is thrown.

Happy to create a PR for this, if that would be in your interest.


> Probably it really makes sense to enable caching during tests? Should we create a new issue for this?

To be honest: this will be a bit of a task. Yes, I would strongly suggest that cache is tested. Because hardly any site runs without cache. However, it's a bit tricky, as the cache would have to be deleted from one test to the next to have a reproducible environment. But then again, the first call to a function might result in a different result than the second, due to the caching. And in many cases, things are only tested once, of course. So all tests that (indirectly) invoke a function that uses cache would need adaption and have to call things twice.

An alternative could be to create a special testing cache which, whenever a value is retrieved that has been cached, retrieve it again from the callback and compares the two results.

But yes, that would have definitively to go in a separate issue.

> @gevorgmansuryan Can you please also take a look into this? Could there possibly be similar issues in your recent `runtimeCache` implementation?

Also, I'd appreciate if this PR could be merged and a new issue for this investigation could be done. It's easier for me to get ahead with my stuff if this PR is merged as-is and I'm no longer stuck with this in my other tests ...

**Comment by luke-** [comment]
> > One small point, if possible, I would prefer when the method `Membership::findMembership(Space $space, User $user): ?membership` would have strict types and does not allow `int` argument. What do you think?
> 
> Thank you for asking for my opinion.
> 
> I personally would suggest to create at least two corresponding methods for the User and Space classes (potentially with caching, too):
> 
> * `User::findUser($user): ?User`
> * `User::findUserAsId($user): ?int`
> * `Space::findSpace($space): ?Space`
> * `Space::findSpaceAsId($space): ?int`
> 
> The `User::findUser` and `Space::findSpace` would do the real work, the other two only get the `$object->id` from the main methods, unless the result is `null`.
> 
> The code in https://github.com/metaworx/humhub/blob/fbc093a9358bb02fe4d8dcdc1309f74396855f85/protected/humhub/modules/space/models/Membership.php#L413-L425 would then be moved into the respective methods.
> 
> This would allow to simplify all these countless occurrences of similar code to be reduced to one function call and you know exactly that you either get a User object - or a UserID respectively - or `null`, no matter what you put in (int, User, or null). In case of an invalid data type, an exception is thrown.
> 
> Happy to create a PR for this, if that would be in your interest.
> 

So if we could introduce two methods:

- `Membership::findMembership(Space $space, User $user): ?self`
- `Membership::findMembershipByIds(int $spaceId, int $userId): ?self`

I'm fine with this too.

But not sure if we need `User::findUser` or User::findUserAsId`. There is already a method `User::findByPk()`. Or did I missed something here?

> > Probably it really makes sense to enable caching during tests? Should we create a new issue for this?
> 
> To be honest: this will be a bit of a task. Yes, I would strongly suggest that cache is tested. Because hardly any site runs without cache. However, it's a bit tricky, as the cache would have to be deleted from one test to the next to have a reproducible environment. But then again, the first call to a function might result in a different result than the second, due to the caching. And in many cases, things are only tested once, of course. So all tests that (indirectly) invoke a function that uses cache would need adaption and have to call things twice.
> 
> An alternative could be to create a special testing cache which, whenever a value is retrieved that has been cached, retrieve it again from the callback and compares the two results.
> 
> But yes, that would have definitively to go in a separate issue.

I've created an issue here: https://github.com/humhub/humhub/issues/6462

> 
> > @gevorgmansuryan Can you please also take a look into this? Could there possibly be similar issues in your recent `runtimeCache` implementation?
> 
> Also, I'd appreciate if this PR could be merged and a new issue for this investigation could be done. It's easier for me to get ahead with my stuff if this PR is merged as-is and I'm no longer stuck with this in my other tests ...

I'm quite sure we can merge this PR. But it would be good if @gevorgmansuryan can take a look into it before.

**Comment by martin-rueegg** [comment]
> > > One small point, if possible, I would prefer when the method `Membership::findMembership(Space $space, User $user): ?membership` would have strict types and does not allow `int` argument. What do you think?
> > 
> > 
> > Thank you for asking for my opinion.
> > I personally would suggest to create at least two corresponding methods for the User and Space classes (potentially with caching, too):
> > 
> > * `User::findUser($user): ?User`
> > * `User::findUserAsId($user): ?int`
> > * `Space::findSpace($space): ?Space`
> > * `Space::findSpaceAsId($space): ?int`
> > 
> > The `User::findUser` and `Space::findSpace` would do the real work, the other two only get the `$object->id` from the main methods, unless the result is `null`.
> > The code in https://github.com/metaworx/humhub/blob/fbc093a9358bb02fe4d8dcdc1309f74396855f85/protected/humhub/modules/space/models/Membership.php#L413-L425 would then be moved into the respective methods.
> > This would allow to simplify all these countless occurrences of similar code to be reduced to one function call and you know exactly that you either get a User object - or a UserID respectively - or `null`, no matter what you put in (int, User, or null). In case of an invalid data type, an exception is thrown.
> > Happy to create a PR for this, if that would be in your interest.
> 
> So if we could introduce two methods:
> 
>     * `Membership::findMembership(Space $space, User $user): ?self`
> 
>     * `Membership::findMembershipByIds(int $spaceId, int $userId): ?self`
> 
> 
> I'm fine with this too.
> 
> But not sure if we need `User::findUser` or User::findUserAsId`. There is already a method `User::findByPk()`. Or did I missed something here?

If you're referring to [User::findIdentity()](https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/User.php#L329), than yes, that's kind of what I meant. And it is not typed at all, neither with the input, not the output.

I would personally allow `User|int|string|null` for input. There are so many places in the code, where this could be used:

https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/Group.php#L273
https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/Group.php#L345
https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/Group.php#L355-L356
https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/Group.php#L385-L386
https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/User.php#L580
https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/UserFilter.php#L31-L35

And there are potentially many more if considering modules.

Having those functions, for the Membership class we only require one as the rest is taken care of in the User and Space classes.

What is the advantage of having a strongly typed input, if the type is verified in the function and throws an exception, as invoking the function with a wrong type would?

**Comment by martin-rueegg** [comment]
> @gevorgmansuryan Can you please also take a look into this? Could there possibly be similar issues in your recent `runtimeCache` implementation?

As a matter of fact, there are.

For example here: https://github.com/humhub/humhub/blob/9a28225efd9e1e6464c261d7685866e84c3200d9/protected/humhub/modules/user/models/User.php#L331-L333

Also in the User model, there is no reset of the cache when a record is updated. This is partly solved in #6463. However, it is quite complicated, as the records can be manipulated by not only the following functions (which can be intercepted to delete the cache) but by any sql query behind the scenes. This is certainly something to keep in mind. Also, the functions marked with an asterisk below, do potentially manipulate multiple records. Since the cache stores the entries with a hashed key, there is no way to selectively flush let's say all User entries. Instead, the entire cache needs to be flushed. An alternative approach could be to create a dedicated RuntimeCache class that allows to 

- configure the storing backend (defaulting to the current setting)
- possibly allows to configure includes and excludes (to not have to entirely disable the cache in console settings)
- maybe keep track of the plain-text keys, so that flushing with a wildcard would be possible

The following model methods affect records (may be incomplete):

- `model::save()` => `model::afterSave()`
- `model::delete()` => `model::afterDelete()`
- `model::deleteAll()`*
- `model::updateAll()`*
- `model::updateAllCounters()`*

*) Functions marked with an asterisk do potentially manipulate multiple records. Hence, the entire cache needs to be flushed. See also above.

See https://github.com/humhub/humhub/pull/6463/files#diff-65dd9f5389478b955980a0410c155bd62e7cdc27f28eebc2f34d0c6bde4741ca for possible workarounds.

**Comment by martin-rueegg** [comment]
There is another situation that needs consideration:

- updating a `content` record should clear the associated record cache
- updating a `contentcontainer` rechord should also clear the parent record

This would require to make the current naming convention for cache key (ie. `$model_class#$pk`/`$object_class#$object_id` mandatory in order for the detail records (`content`/`contentcontainer`) to delete their parent records.

**Comment by martin-rueegg** [comment]
@gevorgmansuryan Is there any progress on reviewing this?

**Comment by martin-rueegg** [comment]
@gevorgmansuryan thanks for having a look into this. By "main PR" you're referring to this one (#6457)?

Could you elaborate on why a `behavior` would suit better than the version using a `trait`? Since caching does not happen automatically, but by doing it explicitly, would it not also suit to do it by intercepting the delete and update methods, which in most cases do not even need to be touched if the trait and the enhanced RuntimeCache implementation from #6482 are used.

**Comment by gevorgmansuryan** [comment]
> By "main PR" you're referring to this one (#6457)?
@martin-rueegg yes

I'll take a look to https://github.com/humhub/humhub/pull/6482

**Comment by martin-rueegg** [comment]
@gevorgmansuryan thank you. Looking forward for your feedback.

@luke- shall we then merge this PR into `develop`, and from there into `statable` and `next`, so we can move forward to review the PRs that are building on top of this one?

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@martin-rueegg 

> @luke- shall we then merge this PR into `develop`, and from there into `statable` and `next`, so we can move forward to review the PRs that are building on top of this one?

Done. Thank you for the fix.

**Pull request merged**
