### PR TITLE
Enh: Improve Codeception Test Speed

### PR DESCRIPTION
**Pull request by luke-**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by martin-rueegg** [comment]
@luke- Is that something we could use/try in `next`?

**Comment by luke-** [comment]
@martin-rueegg I'm a bit unsure about this, because I'm not a codecept/phpunit pro. What do you think about this approach?

**Comment by martin-rueegg** [comment]
Well, as long as the DB supports transactions (in our automated case this is mysql and hence no problem) it would certainly be a good idea. And it uses original codecept/phpunit features. So if we do not trust those, we should not use it as a testing framework! :-)

If we try it on `next` now, we would gather enought experience until we get to beta phase. So we could still un-do it...

**Comment by martin-rueegg** [comment]
Looks not too bad if only one test is failing....
https://github.com/humhub/humhub/actions/runs/5900208082/job/16004027976?pr=5869#step:18:1466

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look into the one failing test?

**Comment by yurabakhtin** [comment]
@luke- Fixed here https://github.com/humhub/humhub/pull/5869/commits/308ffd8dbfaf6439f1d8aeec134739e98ba43fba.

**Pull request merged**
