### PR TITLE
WIP: Implement parent spaces

### PR DESCRIPTION
**Pull request by Fr13dr1ch99**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
Create a function to use a space as parent space.

### CODE REVIEW

**Comment by buddh4** [comment]
Please add some more information about your changes and how it affects the platform. A parent space concept should consider following topics:

 - Content visibility
 - Content search
 - Membership management and permissions
 - Space visibility
 - Space permissions

**Comment by Fr13dr1ch99** [comment]
> Please add some more information about your changes and how it affects the platform. A parent space concept should consider following topics:
> 
> * Content visibility
> * Content search
> * Membership management and permissions
> * Space visibility
> * Content Streams

Thank you for your reply. At the moment the parent space is only a abstraction layer to make spaces more clearly arranged. It does not contain any inheritance structure.
I will change this to WIP.

**Comment by buddh4** [comment]
@Fr13dr1ch99 Are you still working on this, or should we close this PR?

**Comment by Fr13dr1ch99** [comment]
@buddh4 Sorry I have no time at the moment to working on this project.
You can close this request.

**Pull request closed without merging**
