### PR TITLE
Fix #6744: Make sure to call humhub\components\Module::update() on Mo…

### LINKED ISSUE #6744: Check module requirements before install/update reading the new requirements.php file in modules
I would have expected `Module::update()` here. Do you have an idea?

https://github.com/humhub/humhub/blob/374501b9d30fe5c5df634870a2c7e690e9a41f16/protected/humhub/modules/marketplace/components/OnlineModuleManager.php#L176

_Originally posted by @luke- in https://github.com/humhub/humhub/pull/6550#discussion_r1427836637_

### PR DESCRIPTION
**Pull request by luke-**
…dule update

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Can you please check. Do you see any problems here?

**Comment by yurabakhtin** [comment]
@luke- I don't see, because I don't find any module which uses the method `beforeUpdate()` so at least for now it always returns `true` and the new code works as before.

**Review by yurabakhtin — APPROVED** [review]

**Comment by luke-** [comment]
@marc-farre Please simply overwrite the `update()` method. I think  we could deprected `beforeUpdate()` in future.

**Comment by marc-farre** [comment]
@luke- @yurabakhtin Thanks! Yes, I think `beforeUpdate()` and `afterUpdate()` should be marked as deprecated because:
- They aren't used anyway (I've checked on most of the modules)
- If they were used, they didn't work, so removing them won't change anything
- They are useless, as we can overwrite the `update()` method
- It adds complexity in the code
- They could be confusing as we also have before and after update events in the OnlineManagerModule

I've added a commit to mark them as deprecated: https://github.com/humhub/humhub/pull/6799/commits/719e9777fb63ebae46bd4900ab9d4ca571f583da
You can remove of course it if you think it's a bad idea.
I can reference this PR in the README and add the depreciations in the doc if you want.

**Comment by luke-** [comment]
@marc-farre 
> I've added a commit to mark them as deprecated: [719e977](https://github.com/humhub/humhub/commit/719e9777fb63ebae46bd4900ab9d4ca571f583da) You can remove of course it if you think it's a bad idea. I can reference this PR in the README and add the depreciations in the doc if you want.

Thanks for this!

**Pull request merged**
