### PR TITLE
Fix #60 "No answered yet" filter not working

### LINKED ISSUE #60: Beautify and optimize login and registration pages

### PR DESCRIPTION
**Pull request by MasterHans**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by MasterHans** [comment]
Hello everybody,

The reason that caused the issue:

The polls page started from **protected\modules\polls\controllers\PollControler** from this view protected\modules\polls\views\poll\show.php

This view calling **humhub\modules\stream\widgets\StreamViewer** and passing **$filters** parameter 
to it. Parameter **$filters** defined in show.php explicitly.

```
$filters = [
     'filter_polls_notAnswered' => Yii::t('PollsModule.widgets_views_stream', 'No answered yet'),
     'filter_entry_mine' => Yii::t('PollsModule.widgets_views_stream', 'Asked by me'),
     'filter_visibility_public' => Yii::t('PollsModule.widgets_views_stream', 'Only public polls'),
     'filter_visibility_private' => Yii::t('PollsModule.widgets_views_stream', 'Only private polls'),
```


To draw filter and use it **StreamViewer** widget istanchuate  **WallStreamFilterNavigation** object wich extended from **FilterNavigation**.
**$filters** parameter passed to **WallStreamFilterNavigation** as a **definition** parameter. 

```
       $filterNav = ($this->showFilters && !empty($this->streamFilterNavigation)) ? call_user_func($this->streamFilterNavigation.'::widget', [
            'definition' => $this->filters
        ]) : '';

```
Filter **definition** can be used to manipulate the default settings of a filter.
Filters will only be added either if the definition is empty or the **filterId** is present in the definitions.

If the **definition** parameter is empty then filter will be created from **humhub\modules\stream\models\filters\DefaultStreamFilter**. To check this you could look into **SpaceController** and it's view **home**. Here we did not pass the **filters** parameter to **StreamViewer** and the default filter with its settings is drawing.

So, we explicitly passed filters parameters but we have not any settings for these brand new filters. JS module 
**humhub.stream.StreamEntry.js** get it to handle it. Filters are drawn but it did not work.

I have created **PollsStreamFilter** and set it to the **$filters** parameter which I have mentioned above.

Thank's
Alex

**Comment by luke-** [comment]
@buddh4 can you take a look?

**Comment by buddh4** [comment]
You can not add a stream filter of the polls module to the core. The core should not know anything about the polls module. This has to be fixed in the polls module.

**Comment by luke-** [comment]
Here you can find the Polls module: https://github.com/humhub/humhub-modules-polls

**Comment by MasterHans** [comment]
> You can not add a stream filter of the polls module to the core. The core should not know anything about the polls module. This has to be fixed in the polls module.

@luke- @buddh4  Thank's got it!

**Pull request closed without merging**
