### PR TITLE
File hash for download url

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Issue: https://github.com/humhub/humhub/issues/4752

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin FYI, i have renamed the attribute `hash` to `hash_sha1`.

**Comment by buddh4** [comment]
In case a file somehow is missing in the store, the `File::getUrl()` will throw an error, since it can not create a hash. Should we maybe consider a more failsave approach and just leave out the hash in case there is no matching file in the store due to data inconsistency? I saw this issue in a test case in which I just created an empty file model, not sure how often this may occure on a production system.

**Comment by yurabakhtin** [comment]
@buddh4 Could you tell us how to reproduce the error from `File->getUrl()` step by step?

> here we need to create a file manually and then add the file to the store.

Please tell me where I can create a file manually because I cannot find such feature in back-office, thanks.

---

Probably we have the error here https://github.com/humhub/humhub/pull/4769/commits/ffcdcc6d54b37a69f5719fad804c55a11c80fd71#diff-2f3a5cf58d46a6971793c97d7c4defb317661fce7c7cb141d28467442049dbf9R82

@luke- Do you think we really need it there? I think at least it should be changed to `$file->saveHash();` because the `$file` is provided as a function argument. But I think we don't need this because the same function is called in the parent `File->afterSave()`.

The second case https://github.com/humhub/humhub/pull/4769/commits/ffcdcc6d54b37a69f5719fad804c55a11c80fd71#diff-2f3a5cf58d46a6971793c97d7c4defb317661fce7c7cb141d28467442049dbf9R93 I don't find where it may be used.
Here we can add a checking like `if (isset($this->file) && ($this->file instanceof File))`.

**Comment by luke-** [comment]
I think it's primarily about calling an "is_file" before the sha function.

To reproduce I would:

- Upload some files
- Set sha columns to null 
- Delete files in filesystem (uploads/files) 
- Try access files

**Comment by yurabakhtin** [comment]
@luke- Thanks for the steps, I could reproduce the error and fixed in the PR https://github.com/humhub/humhub/pull/4813

**Comment by buddh4** [comment]
@yurabakhtin Here are the test cases which failed: https://github.com/humhub/humhub/pull/4686/files#diff-d0c6bdb00b33daa3f05874e2c6428e3e61e88635795e2d59b13ecf194b4f1ff1R196 but should be ok with your fix. I'll run the test with your fix later.

**Pull request merged**
