### PR TITLE
Display all newer comments after current comment

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub/issues/5956

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Looks really good. In my tests I had a problem with comments with sub-comments.

e.g.
image

image

**Comment by yurabakhtin** [comment]
@luke- 

> e.g. image

What do you mean here?
Yes, when click on the link "Show previous 10 comments" - only 10 comments are loaded even if there are more comments in comment.
In previous version we also loaded only 10 latest comments when link text was "Show all comments", i.e. only 8 additional comments were disaplyed after the click, but currently 10 additional comments are really loaded, please review this screenshot and let me know if something should be improved:

load_comments

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/5981/commits/cd71d46bfae26af3137fa1205737b659d71cb93c for fixes:
- display sub-comments of the current parent
- integer params

display_sub-comments

Do you agree to add padding top and bottom for the grey area of sub-comments inside the yellow current comment?

**Comment by luke-** [comment]
@yurabakhtin 
 
> What do you mean here? Yes, when click on the link "Show previous 10 comments" - only 10 comments are loaded even if there are more comments in comment. In previous version we also loaded only 10 latest comments when link text was "Show all comments", i.e. only 8 additional comments were disaplyed after the click, but currently 10 additional comments are really loaded, please review this screenshot and let me know if something should be improved:
> 

Sorry for the confusion. The screenshot 1 is correct. So nothing to do here.
From my side anything looks fine when the padding is added.

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, a padding would be nice!

Commit https://github.com/humhub/humhub/pull/5981/commits/6c54c8abc501d82863fda3c08dc77da08c995145:

sub-comments-styles

**Review by luke- — APPROVED** [review]

**Pull request merged**
