### PR TITLE
Attached files browser caching, fixes #2091

### LINKED ISSUE #2091: Posts images are being served as dynamic content, not using browser cache
I'm running Humhub on a wireless network (city size), our (self) hosting and bandwith is reaching its limits, we need to squeeze every little bit of performance.

Deployed last friday, already have more than 700 users, 80-160 concurrent, people love it.

Current setup is nginx, php-fpm, mariadb and redis for cache and sessions.

I just realized images are being served as dynamic content, not directly from disk, that is a huge performance blow, if nginx could serve those images directly the server would fly.

Don't know how rooted is this behavior to your architecture but seriously, this could be that low hanging fruit which could fire your scalability to the clouds.

See here, every time I hit refresh the content images are being re-downloaded.

pic34

### PR DESCRIPTION
**Pull request by acs-ferreira**
Using ETag and max-age

### CODE REVIEW

**Comment by buddha87** [comment]
The etag won't be neccessary either, since the files do not change and in your implementation you'll return the same etag for a file anyways. I think we just should set the 'cacheControlHeader' to a reasonable value, a year seems to be an overkill.

I did some tests with cacheControlHeade only and this had no effect, somehow the beforeAction of yii\filters\HttpCache returns before applying the header in this case.

I added the following line to my humhub\modules\file\actions\DownloadAction (without the use of a filter) and it worked:

`Yii::$app->response->headers->add('Cache-Control', 'public, max-age=604800');`

Either we use this approach or add something like this to the HttpCache filter:

`'lastModified' => function ($action, $params) {
        return time();
    },`

**Comment by acs-ferreira** [comment]
IMO, my approach is the best one, because:

- it set a never expire header with the `max-age = 1 year`, see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> To mark a response as "never expires," an origin server sends an Expires date approximately one year from the time the response is sent.

- it generates a unique ETag for each file, it remains the same ETag even after cache clearing

But if in your opinion your approach is better, i'm just contributing after all, not owning ;)

**Comment by buddha87** [comment]
Yeah I understand the purpose of the etag and the max-age. I just tought the one year caching is a bit much, but I think its ok. Thanks for the pr ;)

**Comment by buddha87** [comment]
We'll merge this after the 1.1.2 release.

**Pull request merged**
