### PR TITLE
Fix for Allow users to invite by link #5699

### PR DESCRIPTION
**Pull request by funkycram**
Fix for https://github.com/humhub/humhub/issues/5699

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@funkycram  The option `enableEmailField` is intended for the admin interface or automatic registrations (via LDAP/OAuth) and does not validate the email address. 

We need to find another workflow here.

a.) The easiest way: The initial secret link URL does not lead to the 'registration' directly instead to a new dialog where the user first only has to enter the email. Then he receives an e-mail with a link, validates his e-mail address there and the `/registration` starts as before.

b.) We introduce a new dialogue, directly after the login/registration. Similar to TwoFactor Auth. There, users without an email address are asked to enter an email address and verify it directly. (This step could be omitted if E-Mail Required is set to False). The disadvantage here would be that users could not reset their password until they have set  a validated e-mail.

c.) We integrate an e-mail validation directly into the registration form. 

d.) We only allow the "Register by Link" feature when `$userModule->emailRequired` is set to `false`.

**Comment by funkycram** [comment]
Thanks @luke- for these proposals. 

As the registration process is already a little complex, I think it's better to separate the registration by link. So I took option B.

It works also if User::emailRequired is set to false (I redirect to the registration form).

I also separated the different registration types here (and fixed the value which was already `1` in the Source column):
image

What to you think about this PR?

**Comment by luke-** [comment]
@funkycram Thanks, looks good, that's how I thought of option A. :-)

Can you perhaps add a few (acceptance) tests for this?

Especially for such features  with different edge cases (e.g. `emailRequired` true/false) it would be good to have  such things covered by tests.

**Comment by funkycram** [comment]
I have no experience in test management...
However, I can try, but I have limited time, because @samuk is the one who pay me for this job and I already spend quite some time one it...

As far as I can see, I could add something like this in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/tests/codeception/acceptance/InviteCest.php:

```php

    /**
     * @param AcceptanceTester $I
     * @throws \Exception
     */
    public function testDashboardInviteByLink(AcceptanceTester $I)
    {
        $I->wantTo('ensure that inviting external users by link works.');

        $I->amUser();
        DirectoryMemberPage::openBy($I);

        $I->click('Invite new people');
        $I->waitForText('Invite new people', null, '#globalModal');
        $I->click('Invite by link');
        $I->waitForText('You can invite external users who are currently not registered via link.');
    }
```

But I understand that the main process you want to test is the registration part. But I cannot find these tests in `acceptance`. It's more in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/tests/codeception/functional/RegistrationCest.php

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@funkycram  I've added some basic tests here: https://github.com/humhub/humhub/commit/dbf39aa49707bfd1a1b6d973f1aac51360b43ffb

I have removed the support when no email address is required. This added too much  special handling for this edge case (e.g. space ID in session with approval).  See here: https://github.com/humhub/humhub/commit/f860b27f2f182b8113fed6dc6bf03d15e12740bf

Can you please check this.

**Comment by funkycram** [comment]
@luke- A very big thank you for the work you have done!
And I see that it was quite a job!
Next time, I will plan the time to spend to add or update the automatic tests.
I did a quick test and invitations by link works well.
Thanks again! Marc.

**Pull request merged**
