### PR TITLE
Enh: Added unit tests in live/activity/comment module.

### PR DESCRIPTION
**Pull request by buddh4**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by luke-** [comment]
I think we should only hotfixes into the `master` Branch.
Can we merge this into the `develop` branch?  Or is there something against this?

**Comment by ArchBlood** [comment]
Normally you'd only want live branches to have tests, and seeing as develop branch is more lively it should take priority on tests than master

**Comment by buddh4** [comment]
Those tests were written prior to 1.6 release. As long as the tests pass I don't see any issues adding them to master. Would rather argue why such tests did not exist prior 1.6 release. But I can also push them to dev.

**Comment by buddh4** [comment]
The tests in this pr do not really add much coverage or are very important, but generally I think tests should be part as early as possible. Adding tests to master assures that the code works in v1.6.2+ while adding them to dev assures it works in v1.7.0+. New tests do not break existing code or compatibility. Also hotfixes should be come with tests assuring the fix works...

**Comment by luke-** [comment]
I'm mainly interested in a clear policy with the branches. This PR can of course merged into master without any problems.

Regarding the policy, I would prefer to have only important fixes (incl. corresponding tests) and no other new code in this branch.
Of course, we can also generally allow new test code here.

**Comment by luke-** [comment]
@buddh4 You can easily rebase in GitHub, just edit the PR and change the target.

**Pull request closed without merging**
