### PR TITLE
Add support to Amazon SQS Queue driver

### PR DESCRIPTION
**Pull request by acs-ferreira**
https://github.com/yiisoft/yii2-queue/blob/2.1.0/docs/guide/driver-sqs.md

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Starting with 1.3 we keep composer.lock in git. When you modify composer.json please run composer install and commit composrr.lock as well. What have u changed with this pr? There is no package added or deleted.

**Comment by danielkesselberg** [comment]
I see. You changed yii2-queue from ~2.0.0 to ~2.0 which includes version 2.1.0 now. Looks fine for me. When it works with php5.6 and our yii version.

**Comment by acs-ferreira** [comment]
I prefer that HH team update composer.lock after runnibg internal QA tests. Is it bad?

**Comment by danielkesselberg** [comment]
Closed via https://github.com/humhub/humhub/commit/45184bc554f423b1a59ed9118fb6b6eee66fc59b

**Pull request closed without merging**
