### PR TITLE
Why missing 'en-US', 'en-GB'?

### PR DESCRIPTION
**Pull request by tomofu74**
We need to translate options... don't we?

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:
system messages required to rebuild.

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
The main difference between "en-US" and "en-GB" are currently Locale specific details like the date format.

However, it is possible to overwrite individual terms in the different variants using a local translation file.
I would currently rather not create all language files for this automatically. Also to keep the number of files as low as possible.

I'm also not sure that our translation community software supports this.

**Comment by ArchBlood** [comment]
> The main difference between "en-US" and "en-GB" are currently Locale specific details like the date format.
> 
> However, it is possible to overwrite individual terms in the different variants using a local translation file.
> I would currently rather not create all language files for this automatically. Also to keep the number of files as low as possible.
> 
> I'm also not sure that our translation community software supports this.

Not only this but English is already a default language that's used throughout the whole project so adding it wouldn't really matter. :thinking:

**Comment by tomofu74** [comment]
Yes, English is already default and it wouldn't really matter to use system.
But, Humhub announces Available translations list shows "en-UK", though it is not appeared on Language selection list on default system, isn't it ? https://docs.humhub.org/docs/admin/translations/
By the way, we just only want to use specific wording for specific member with this English choice. So it is useful specific English member.

**Comment by ArchBlood** [comment]
To be honest `en-UK` should be changed to `en-GB` because this is the actual locale code for the UK, so that is a typo in the docs, but you can already use the translation overwrite & limited allowed languages even without them being added to `i18n.php` so I'm still not seeing actual use of it being added. If something in English needs overwritten then do it through the overwrite option, if you see a grammar issue or typo then you'll have to find the exact file that has the English wording needed changed, as there are no `/messages/en-US` or `/messages/en-GB` source file directories to these languages. :thinking:

### Profile Languages
Screenshot_2

### Global Languages
Screenshot_1

### Limited Allowed Languages
Screenshot_3

**Comment by luke-** [comment]
If there are several wording differences between en-US (default) and en-GB, we can also create 'en-GB' language files.
But if possible I would try to find a consistent wording for both language variants.

**Comment by ArchBlood** [comment]
> If there are several wording differences between en-US (default) and en-GB, we can also create 'en-GB' language files.
> But if possible I would try to find a consistent wording for both language variants.

@luke- I believe this [here](https://tinyurl.com/y5wkuete) hits the nail on the head when differentiating the two English languages

**Comment by luke-** [comment]
@ArchBlood thanks!

I think the most important are the date & time formats.  

We should try to find a wording that fit well for both language variants (US & GB). If this is not possible, we should create these particular language files manually.

@tomofu74 Would that solve your issue?

**Comment by tomofu74** [comment]
That wil be OK and We'll try to translate each time according to the customer's request.
Thank you ArchBlood, loke-.

**Comment by luke-** [comment]
@tomofu74 Great, please feel free to create a PR with the changed wordings.  Thanks!

**Pull request closed without merging**
