### PR TITLE
Marketplace / Modules Redesign

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature
- [x] Code style update
- [x] Refactor

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] All tests are passing
- [ ] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/humhub-internal/issues/9

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by felixhahnweilheim** [comment]
Hi, I really like the new design but I have found two small issues:

**Marketplace page:** On mobile phone the cards don't have the same width.

Screenshot 2023-07-12 at 21-27-44 Dashboard - Felix Hahn Development

**Modules page:** The "information" option links to the Marketplace page with the module's ID as search key. I think this is an unnecessary step. There is not more information than on the Module page. Just when you click again "information" from the dropdown, you will get more information. This might be confusing for new users.

Step1

Next problem: When clicking on information for the Task module, I first see the "Meetings" module. (Because the word "tasks" is used there, too.)

Step2

And: For custom modules (directly uploaded), you just see "No modules found"

**Comment by felixhahnweilheim** [comment]
Another issue: I now see the Marketplace menu item at community.humhub.com. But (of course) I don't have access to it.

**Comment by luke-** [comment]
> Another issue: I now see the Marketplace menu item at community.humhub.com. But (of course) I don't have access to it.

@yurabakhtin Can you please check?

**Comment by yurabakhtin** [comment]
@luke- Please review PR https://github.com/humhub/humhub/pull/6429.

**Comment by luke-** [comment]
> Previously it was also possible to see information of a custom module (the README file was displayed in a modal window). But I guess this is not so important.

Yes, this feature has been omitted. Maybe we will add it later somehow.

The other points should be fixed.

**Pull request merged**
