### PR TITLE
Lock search index while reindexing

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
https://github.com/humhub/humhub/issues/5419

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Is there a waiting time between retries?

**Comment by yurabakhtin** [comment]
> Is there a waiting time between retries?

@luke- The content search jobs are extended from `LongRunningActiveJob` which uses [the value](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/queue/Module.php#L26) for ttr: `$longRunningJobTtr = 60 * 60`.

**Comment by yurabakhtin** [comment]
@luke- Maybe do you mean [RetryAcquireTrait](https://www.yiiframework.com/doc/api/2.0/yii-mutex-retryacquiretrait)?
But I see it is used only for `FileMutex` and `PgsqlMutex` but currently the `MysqlMutex` is used in [config](https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L170-L172).

**Comment by luke-** [comment]
@yurabakhtin Yes, I mean something like the Mutex Retry Timeout.

`Ttr` just seems to be the maximum execution time.

With your solution I am afraid that the retry will happen immediately (e.g. if there is a queue with workers).

Ideally a time of e.g. 5 minutes passes until the next retry.

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, I mean something like the Mutex Retry Timeout.

Done in the commit https://github.com/humhub/humhub/pull/6934/commits/e810cb8e0576b54dec672abee590471d98c41f32.

**Review by luke- — APPROVED** [review]

**Pull request merged**
