### PR TITLE
Fix #6228: Administrators allowed to manage users cannot invite by em…

### LINKED ISSUE #6228: Administrators allowed to manage users cannot invite by email or by link if disabled in the settings
### What steps will reproduce the problem?

Disable invitations:
image

As an admin allowed to manage users, invite new people:
image

#### Invite by email

image

#### Invite by link

image

#### Invite by email

The email is send.

#### Invite by link

The invite link works.

#### Invite by email

After sending the mail, we have:
image

#### Invite by link

When opening the link:
image

This is of course because of the settings disabling invitations by email and link, but if the "Invite new people" is displayed, it should work for admins allowed to manage users.

### Additional info

Another option would be to not display the button "Invite new people" in the User Administration: `/admin/user/add`:
image

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13 and 1.14

### PR DESCRIPTION
**Pull request by yuriimaz**
…ail or by link if disabled in the settings

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by luke-** [comment]
@yuriimaz Thanks, can you please create this PR against the Master branch?

**Review by luke- — APPROVED** [review]

**Comment by yuriimaz** [comment]
@luke- Create a separate PR or change this one?

**Comment by yuriimaz** [comment]
I created a new PR and you already merged it. PR https://github.com/humhub/humhub/pull/6307

**Comment by luke-** [comment]
@yuriimaz Thanks, I'll close this one.

**Pull request closed without merging**
