### PR TITLE
#173 fix Captcha-in-Registration

### PR DESCRIPTION
**Pull request by ultimocoder**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ArchBlood** [comment]
I'm not exactly sure what this P/R aims to accomplish, all it does is comment out some lines of code and remove `registrationSendMessageMailContent` from use in the view file. `DataSaved::widget()` should be avoided to be honest as it's not really needed anymore. 🤔

**Comment by ultimocoder** [comment]
This PR has been raised to Fix below issue 

https://github.com/humhub/humhub-internal/issues/173

**Comment by ultimocoder** [comment]
Thank you for the review. The task was to remove the captcha, so I have commented out the frontend code and removed other one. I didn't fully remove it from the frontend as it might impact other areas. Please let me know if you have any questions.

**Comment by ultimocoder** [comment]
Kindly reject this PR is it is done from wrong git account.

**Pull request closed without merging**
