### PR TITLE
File versioning

### PR DESCRIPTION
**Pull request by yurabakhtin**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] All tests are passing
- [x] Changelog was modified

**Other information:**
Issue: https://github.com/humhub/cfiles/issues/121#issuecomment-920634420

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Looks good. Can you please add some tests? (I am reviewing the names of the methods. ) Thanks!

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Looks good for me! Can you please add some unit tests here? I'll then adapt the documenation...

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please add some unit tests here?

I don't find what we can test there from core side currently because we don't have any core model which implements `AttachedFileVersioningSupport`, only if I will add tests on the CFiles modules, but currently we already have a single acceptance test there.

**Comment by luke-** [comment]
@yurabakhtin Ok, let's add some acceptance tests in the CFile module. This issues is related to core testing https://github.com/humhub/humhub/issues/4845 - We should add some dummy module or dummy content to improve unit testing...

**Pull request merged**
