### PR TITLE
Fixed error when authclient is not providing an id

### PR DESCRIPTION
**Pull request by luke-**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by buddh4 — APPROVED** [review]

**Comment by ArchBlood** [comment]
Still throws an undefined index: id in /home/USER/public_html/protected/humhub/modules/user/authclient/AuthClientHelpers.php:65 after testing this with a WordPress OAuth :thinking:

**Comment by luke-** [comment]
@ArchBlood I added a check here, but every AuthClient must return a unique ID.

**Comment by ArchBlood** [comment]
After testing, this now masks the error and doesn't show any on the frontend, which is alright with me

**Comment by buddh4** [comment]
Shouldn't we at least log an error or warning if the id is missing (since its required)?

**Comment by ArchBlood** [comment]
> Shouldn't we at least log an error or warning if the id is missing (since its required)? Or is there an case in which a missing id is ok?

The logs pick up on the error just doesn't display any error on the frontend anymore, I think this was intended so that the user doesn't just get thrown into an error page, but I could be wrong :thinking:

**Comment by luke-** [comment]
There is a log: 
https://github.com/humhub/humhub/pull/4355/files#diff-86f39425a1dae4ffb1fad87da597acd1R86

And also an error message: 
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AuthController.php#L149

**Pull request merged**
